### ISSUE TITLE
Augment format-all-the-code with unibeautify?

### ISSUE THREAD

**Issue by rassie** [doomemacs/doomemacs#1343]
Apparently, there is a project called [Unibeautify](https://unibeautify.com) with mostly the same scope as `format-all-the-code`, but configurable. There is an (apparently) working [Emacs integration](https://github.com/Unibeautify/emacs) by @lassik, the original author of `format-all-the-code`, who seems to be leaning in favor of Unibeautify.

Would adding some support for Unibeautify be in scope for `doom-emacs`?

@lassik if you happen to be summoned to this issue by the mentions or otherwise, could you weigh in on the future of `format-all-the-code` and Unibeautify's Emacs integration, as you see it at the moment?

**Comment by lassik** [comment]
I did indeed get email :) This is fine with me.

Unibeautify.el is much simpler than format-all.el on the Emacs side, because all the complexity goes into the Unibeautify backend (it's a command line program written in TypeScript and runs on Node.js). All the formatter options are specified in a `.unibeautifyrc` file in a project's source directory so we don't need to worry about how to specify formatters and their options in Emacs. As far as I can tell, unibeautify.el doesn't need any customize variables on the Emacs side, but this is not an absolute promise yet :)

The plan is to supply one function to format an entire buffer (which doesn't need to be saved to a file, or even visiting a file) and another function to format only a region of the buffer (ditto). We haven't yet discussed how to implement region-only formatting with Unibeautify, but unibeautify.el will follow whatever decision we make. FWIW, clang-format, prettier and swift-format have built-in support for region-only formatting (https://github.com/lassik/emacs-format-all-the-code/issues/17) so the future is looking promising for editor plugins.

I've been putting off work on Unibeautify, Unibeautify.el (and also format-all) to prioritize other stuff, but I think Unibeautify is the right approach to code formatting so if adoption picks up, I will be motivated to get things done faster. The Unibeautify project also welcomes new people.

In other news, format-all should also support configurable formatting, but since I don't personally need it and people have not been bugging me about it, I've been putting it off. In one thread I deliberately asked people to complain that it's been taking so long and nobody did :D So that's why it's not done yet. I also gave direct commit rights to format-all to some people but it seems everybody's busy with other stuff.

Also Steve Purcell made [reformatter.el](https://github.com/purcell/reformatter.el) some time after format-all was published. It's a roll-your-own-formatter framework and not so much about configuring or selecting formatters. Some language-specific Emacs modes use it to hook into the formatter for that language. I'd like to refactor both format-all.el and unibeautify.el so they are implemented on top of reformatter.el (to avoid duplication of effort) but Steve is extremely busy with other stuff (and I'm busy) so it will probably take at least 6 months unless other volunteers show up.

**Comment by hlissner** [comment]
As of #6369's merge, `:editor format` module has been rewritten, replacing format-all with apheleia. As such I am closing all of its former issues as most of them are no longer applicable. Please open a new issue if this (or other) issues present themselves with the new implementation.
