### ISSUE TITLE
Issue with spell-fu and the documentation

### ISSUE THREAD

**Issue by vikigenius** [doomemacs/doomemacs#4483]
The documentation mentions the following

> If you are not using +flyspell, you will need aspell (and a dictionary) installed whether or not you have +hunspell or +enchant enabled. This is because spell-fu does not support generating the word list with anything other than aspell yet.

However enabling the +enchant option causes spell-fu to mark every word as incorrect, even though aspell and it's dictionary are installed in my system.
Simply switching the option to +aspell fixed the issue.

When using the +enchant option, this is what my words_default.txt contains

```
  -a             list suggestions in ispell pipe mode format
  -d DICTIONARY  use the given dictionary
  -h             display help and exit
  -L             display line numbers
  -l             list only the misspellings
  -v             display version information and exit
Usage: /usr/bin/enchant-2 -a|-l|-h|-v [-L] [-d DICTIONARY] [FILE]
```

Seems like it's trying to use enchant-2 to dump words even though it's unsupported. And thus instead of getting a word list it's getting an error message with usage.

So when I am using spell-fu can I use the +enchant option or not? Does it make a difference ?

**Comment by Delanii** [comment]
From my limited experience, until some expert reacts, you **can** have enchant, flyspell, aspell or anything else enabled in dooms `init.el`; however, what you actually use has to be set-up afterwards in your config or per-buffer.

The default spellchecker is `spell-fu`. Which spellchecker you should use depends on the language you are writing in. For example, spell-fu is usable only for english, last time I checked. I personally use hunspell. I know nothing about how to make enchant work, but you can definitely use it along with spell-fu, or instead. I think they shouldnt be mutually exclusive (since you can use hunpell, flyspell, aspell alongside themselves, if you want to for some reason).

Lastly, from your question, if I understand it correctly, it does not seem to me that this is a bug ...

**Comment by vikigenius** [comment]
@Delanii I am using English, that's why I am using spell-fu since it's supposed to be faster. I don't care about other languages. What do you mean it's not a bug? According to the Docs I can use enchant and spell-fu together, and this is the result if I use them together. Every single word is marked as incorrect. Manually using the ispell-change-dictionary doesn't fix it. Every english word is still marked as incorrect.

**Comment by IllustratedMan-code** [comment]
I have this problem as well. I am pretty sure that it has to do with the order in which the variables are set. 

When I start emacs (with the +hunspell flag on the spell module), the `ispell-program-name` variable is set to `"/sbin/aspell/"` and the `ispell-really-aspell` variable is set to `"0.60.8"` (my current aspell version).

When I toggle `spell-fu-mode` on, everything gets underlined in red and the `ispell-program-name` variable is set to `"hunspell"`. The problem is that `ispell-really-aspell` is still set. `ispell-really-hunspell` does not get set.

This line in spell-fu.el (363) is where the problem lies:
`(or (and ispell-really-aspell ispell-program-name) (executable-find "aspell"))))`
Because the variable `ispell-really-hunspell` does not get set, the line evaluates to `"hunspell"` or in your case `"enchant-2"` which is why the output in words_default.txt returns an enchant-2 error message.

I solved this problem by putting these lines in my config.el file
`(setq ispell-program-name "hunspell")`
`(ispell-check-version)`

This seems easily fixable by putting `(ispell-check-version)` after the setq statement in the spell module

**Comment by zeorin** [comment]
I worked around this by adding the following to my `config.el`:

```elisp
(use-package! spell-fu
  :config
  (ispell-check-version))
```

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
