### ISSUE TITLE
Proposal of a new completion plugin

### ISSUE THREAD

**Issue by ashincoder** [doomemacs/doomemacs#5600]
### Describe your request

By completion plugin I mean the one like company-completion. 

Here is the link to the plugin: https://github.com/minad/corfu

This was developed by the creator of vertico.el

### Briefly explain its use-case

1. Visit https://github.com/minad/corfu
2. Read ;-)

**Comment by shenlebantongying** [comment]
+1

Please also include the batteries to supercharged corfu → https://github.com/minad/cape

**Comment by davidbudzynski** [comment]
There's also an icon package for corfu: https://github.com/jdtsmith/kind-icon

**Comment by anonimitoraf** [comment]
Anyone taken this on? Asking because I might, if/when I get some time

**Comment by iyefrat** [comment]
not at the moment, if there isn't a draft pr on the subject you can be reasonably certain that no one has started significant work yet.

**Comment by anonimitoraf** [comment]
Here's my initial 30 minute shot at it: https://github.com/anonimitoraf/doom.d/blob/master/corfu-config.el

but you need to have these in `packages.el`
```
(package! company :disable t)
(package! corfu)
(package! corfu-doc
  :recipe (:host github :repo "galeo/corfu-doc"))
(package! cape)
(package! kind-icon)
```

and these in `config.el`
```
(add-to-list 'load-path "~/.doom.d/") ;; Or wherever corfu-config.el is
(require 'corfu-config)
```

I'll tidy these up (and make the configs less opinionated and submit a PR) when I get time

**Comment by shenlebantongying** [comment]
@gagbo has a private corfu module (MIT license), it looks nice. 
https://git.sr.ht/~gagbo/doom-config/tree/master/item/modules/completion/corfu

**Comment by gagbo** [comment]
The shift will happen eventually, Henrik seems to want it as well, and he started using my draft module as a starting point. Corfu has been on the radar for a while, I kind of nudged minad into writing `cape` (in Discord conversations, hopefully we'll be able to go live on Discourse soon for better discoverability), since it was important for evil users to have the `C-x` bindings in insert mode.


Feel free to PR a module if/when you have something, but since Henrik started experimenting with it, it _might_ be on the No-PR list, just so you know.

(I don't think I'll PR this one, since I know I won't have the time/motivation to maintain such a central piece of the Doom/Emacs experience, I'd rather wait for the next version of Doom CLI, and maybe provide it as a 3rd party module)

**Comment by illia-danko** [comment]
To me the advantage corfu over company is corfu avoids annoying issue of _hiding line numbers_ on tty: https://github.com/company-mode/company-mode/issues/234
