### ISSUE TITLE
clojure with lsp feature throwing error: (invalid-function lsp!)

### ISSUE THREAD

**Issue by Ramblurr** [doomemacs/doomemacs#6151]
### What did you expect to happen?

When I open a clojure file (in a clojure project), the clojure lsp should work.

### What actually happened?

LSP isn't working. 

Upon opening the clojure file, you get the following error message:

```
File local-variables error: (doom-hook-error hack-local-variables-hook doom-run-local-var-hooks-h (doom-hook-error clojure-mode-local-vars-hook lsp! (invalid-function lsp!)))
```

### Describe your attempts to resolve the issue

- tried fresh doom install from master (42e5763782fdc1aabb9f2624d468248d6978abe2)
- tried on simplest possible clojure project

### Steps to reproduce

1. Install fresh doom from master branch
2. Edit init.el and enable :lang `(clojure +lsp)`, enable :tools `lsp`, disable :completion `vertico`, enable `ivy`
3. doom upgrade + sync + env
4. Open doom
5. Use `lsp-install-server` to install the clojure lsp server
6. Open a clojure project with `SPC p p`, open a clojure file with `SPC p f`

Expectation: lsp works in the clojure file

### System Information

https://pastebin.com/RStKA8TP

**Comment by notgerry** [comment]
Just reinstalled everything and I'm getting the same type of errors when I open a Kotlin or Java file.

`Error (java-mode-local-vars-hook): Error running hook "lsp!" because: (invalid-function lsp!)`
`Error (hack-local-variables-hook): Error running hook "doom-run-local-var-hooks-h" because: (doom-hook-error java-mode-local-vars-hook lsp! (invalid-function lsp!))`

System Info:
https://pastebin.com/gTSf8tbQ

**Comment by howabouthis** [comment]
I'm receiving the same errors when opening Haskell files with Haskell lsp enabled.

`File local-variables error: (doom-hook-error hack-local-variables-hook doom-run-local-var-hooks-h (doom-hook-error haskell-mode-local-vars-hook lsp! (invalid-function lsp!)))`

`Error (haskell-mode-local-vars-hook): Error running hook "lsp!" because: (invalid-function lsp!)`

`Error (hack-local-variables-hook): Error running hook "doom-run-local-var-hooks-h" because: (doom-hook-error haskell-mode-local-vars-hook lsp! (invalid-function lsp!))`

System information: https://pastebin.com/VFBtQDy4

**Comment by Ramblurr** [comment]
I haven't experienced this in quite some time. Closing.
