### ISSUE TITLE
Volar for vue

### ISSUE THREAD

**Issue by Suyashtnt** [doomemacs/doomemacs#6152]
### Describe your request

I would like to be able to use `volar` as the vue language server instead of the default `vuels`.  It is reccomended by Evan You, the creator of vue [here](https://twitter.com/youyuxi/status/1355885175335505920).

### Briefly explain its use-case

Volar has proper vue 3 support and is faster than vuels. It also has better typescript support.

**Comment by gagbo** [comment]
Hello,

Don't mind me, I'm just leaving pointers here regarding implementation/maintenance scoring.

I actually triggered a [revert of the volar support in lsp-mode](https://github.com/emacs-lsp/lsp-mode/issues/3261) because it had an issue that leaked through all lsp clients. It looks like since then that a [separate repo](https://github.com/jadestrong/lsp-volar) appeared to ""safely"" develop specific extension, but they [intend to upstream to lsp-mode soonTM](https://github.com/jadestrong/lsp-volar/issues/1#issuecomment-1034782447)

**Comment by atensity** [comment]
Hi,

just leaving a small update. It seems that lsp-volar has been upstreamed to lsp-mode [in a recent commit](https://github.com/emacs-lsp/lsp-mode/commit/f1b73ddd6c168f85a298f81151c97f60e5267a60), so it should okay to close this issue.

**Comment by Suyashtnt** [comment]
> Hi,
> 
> just leaving a small update. It seems that lsp-volar has been upstreamed to lsp-mode [in a recent commit](https://github.com/emacs-lsp/lsp-mode/commit/f1b73ddd6c168f85a298f81151c97f60e5267a60), so it should okay to close this issue.

Its unreleased

**Comment by sethidden** [comment]
> Its unreleased
Just add `(unpin! lsp-mode)` to your `~/.doom.d/packages.el`, then run `doom upgrade`. Seeing how lsp-mode has ~2 releases per year it's going to be unreleased for a while

**Comment by gagbo** [comment]
Actually, it shouldn't need unpijn since the [last :tools lsp bump](https://github.com/hlissner/doom-emacs/commit/44dee4033fa1d7b5d5c78e8e9b22d123f8fab4de), so `doom upgrade` should be enough, and this issue can definitely be closed

**Comment by Suyashtnt** [comment]
I completely forgot about this issue, closing now!
