### ISSUE TITLE
The fonts which are used by the system are different from the fonts in doom emacs

### ISSUE THREAD

**Issue by ExistingProgrammer** [doomemacs/doomemacs#6192]
### What did you expect to happen?

Icons used by system and doom emacs are same.

### What actually happened?

This is my i3 config. This is how the font characters look in emacs
![image](https://user-images.githubusercontent.com/71560815/158008917-185e68c6-b2c7-4c0b-958d-a9aea344bf0c.png)

But this is how the workspace 7 icon looks outside of emacs
![image](https://user-images.githubusercontent.com/71560815/158008927-d4195ec7-3dab-4def-9a60-b4a5e4c26e85.png)
workspace 1,2,3,5 and 6 looks fine though 
![image](https://user-images.githubusercontent.com/71560815/158008932-3b982d5b-97b8-4852-999c-415d2220be21.png)

Starship prompt in alacritty:
![image](https://user-images.githubusercontent.com/71560815/158008963-5257b617-0415-4b01-ba0e-01e0f69c6a12.png)
Vterm prompt in emacs
![image](https://user-images.githubusercontent.com/71560815/158008978-dbd4159a-7927-4b75-9a60-f79b701b4b26.png)

### Describe your attempts to resolve the issue

Tried searching around in google, to no avail. Tried asking for help in discord aswell.

### Steps to reproduce

Try pasting this character in emacs . It looks like the Github icon I showed before. But, outside of emacs, it looks like the discord icon. Be sure to install nerd fonts!

### System Information

https://pastebin.com/sbELF3aP

**Comment by ohmyhub** [comment]
I have very similar issues using `sway` on `arch` with `nerd-fonts`. I've noticed that syntax highlighting can even change what unicode character ends up being displayed.

Also, the `all-the-icons` weather icons will sometimes show up instead of the intended unicode character.

When I have time later I'll add more information and some screenshots.

**Comment by joachimnielandt** [comment]
I am experiencing the same issue. Trying to set the following in `config.el`, to use the included glyphs:

```
(setq doom-font (font-spec :family "FiraCode Nerd Font Mono" :size 12 :weight 'semi-light)
      doom-unicode-font (font-spec :family "FiraCode Nerd Font Mono" :size 12 :weight 'semi-light)
      doom-variable-pitch-font (font-spec :family "FiraCode Nerd Font Mono" :size 13))
```

When viewing a file that contains one of the desired glyphs, instead it uses the weather font (using `C-u C-x =` to get the font for the glyph shown):
```
             position: 2620 of 6511 (40%), column: 23
            character:  (displayed as ) (codepoint 61556, #o170164, #xf074)
              charset: unicode-bmp (Unicode Basic Multilingual Plane (U+0000..U+FFFF))
code point in charset: 0xF074
               syntax: w 	which means: word
             category: L:Strong L2R
             to input: type "C-x 8 RET f074"
          buffer code: #xEF #x81 #xB4
            file code: #xEF #x81 #xB4 (encoded by coding system utf-8-unix)
              display: by this font (glyph code):
    ftcrhb:-UKWN-Weather Icons-normal-normal-normal-*-17-*-*-*-*-0-iso10646-1 (#x80)
```

**Comment by ExistingProgrammer** [comment]
> The same is happening to me, though I've found that when using doomemacs in the terminal via emacsclient and opening vterm, all of the icons render correctly.

For me running it in the terminal via `emacs` works, but emacsclient does not.

**Comment by loafofpiecrust** [comment]
Thank y'all for digging into this. I've been dealing with weather icons for everything for months. Apparently just adding `:weight 'medium` to `doom-font` caused this, and removing the weight spec fixed it for me! I wonder if this could be fixed in doom or all-the-icons?

**Comment by hlissner** [comment]
OP's original issue is likely due to [these lines](https://github.com/doomemacs/doomemacs/blob/master/lisp/doom-ui.el#L431-L437), which maps all-the-icons' icon fonts to a fixed range in the unicode character table, so icons can be available to all the plugins/modules that depend on it. This has the unfortunate side-effect of overruling the glyphs of any fonts.

Sadly, I'm not sure Doom can do anything about this to resolve all cases. The code-points in use are fixed by the package and by every Emacs plugin that depends on all-the-icons. As a workaround, you can either map specific icons to the font you want:

```elisp
(add-hook! 'after-setting-font-hook
  (set-fontset-font 
    t 
    ?                            ; this is the github/discord glyph OP used
    (font-spec :family "FONT")))   ; replace FONT with the nerd font family name
```

Or remove `doom-init-all-the-icons-fonts-h` from `after-setting-font-hook` and live with the occasional wrong icon in your UI:

```elisp
(remove-hook 'after-setting-font-hook #'doom-init-all-the-icons-fonts-h)
```

Also, try upgrading to Emacs 28.2. Emacs recently switched to Harfbuzz for rendering text. Maybe it'll affect Emacs' font behavior for the better?

> I've noticed that syntax highlighting can even change what unicode character ends up being displayed.

Syntax highlighting in Emacs works by applying faces to a buffer's text, and these faces can influence [how Emacs chooses fonts](https://www.gnu.org/software/emacs/manual/html_node/elisp/Font-Selection.html). If it applies a bold face, but your font lacks a bold variant, it may fall through to another font altogether (typically Symbola). You could try the `set-fontset-font` approach above to overrule this, though.

> For me running it in the terminal via emacs works, but emacsclient does not.

> though I've found that when using doomemacs in the terminal via emacsclient and opening vterm, all of the icons render correctly.

That's because Emacs doesn't handle font rendering in the terminal. The terminal does. So Emacs (and Doom's) default `set-fontset-font` rules are ignored, Doom disables `all-the-icons`, and you sidestep the entire problem altogether. Unfortunately, this means little for us GUI users.

> Upon removing :size and :weight from my configuration, the glyphs seem to be rendering fine. I guess in my case it was a matter of the font not containing the correct information.

This is likely the case. Emacs doesn't do any best-guessing or interpolation when a font lacks a requested weight/size/style. Maybe harfbuzz might improve the situation in 28.X?

-----

In any case, unless we, as an ecosystem, switch over to svg (which would probably be ideal), or we do away with icons altogether, we're stuck with this catch-22 for now, so I'll close this for now. Feel free to follow up here, however. 

Thanks for bringing it to my attention!
