### ISSUE TITLE
Move `magit-status` bind to `<leader>-g-v` to keep `<leader>-g-g` reserved for `doom/escape`

### ISSUE THREAD

**Issue by Davoodeh** [doomemacs/doomemacs#6297]
### Describe your request

As `C-g` is the "get me out of here" bind, I was thinking that it's not a cool symmetry that VCS/Magit binds are `<leader>-g-` in Doom.

It would be so nice and more noob friendly to move `<leader>-g` binds to `<leader>-v` (as in Version Control), or at the very least move `<leader>-g-g` to `<leader>-g-v` and have `<leader>-g-g` bound to `doom/escape` by default.

To word it in another way:

1. I suggest to move all `<leader>-g` binds to `<leader>-v` and have it bound to `doom/escape`
2. OR at least move`<leader>-g-g` bind to `<leader>-g-v` and have it bound to `doom/escape`.

Reason: It is more Emacic

If this is a stupid idea, I'm sorry for your time :D'

**Comment by Infinidoge** [comment]
In the case of option one, I'd suggest that `<leader> g g` become `<leader> v v` for the sake of keeping it a repeated key, I've found it faster.

However, for me personally, I think `<leader> g g` is alright as it is, since `doom/escape` is mainly bound to `ESC`. `C-g` is the existing Emacs-centered keybinding, while `ESC` is Evil. That being said, given that `v` is right next to `g` (on US keyboards, at least), I don't think it would be much of a problem to change.

**Comment by snuffop** [comment]
Well for that matter for magit  use  <leader> g s   <  mnemonic for (g)it (s)tatus  and move Stage (hunk and file)  to <leader> S (h&f) respectively

**Comment by iyefrat** [comment]
Imho it's more noob friendly to have git on `g`, having it on `v` for version control is not that intuitive when git is by far and away the most widely used one. Also, `<leader> g v` loses the intuitive repeated keypress for the status buffer.

Also, all of `<leader> g` is for git keys, having `C-g` there as well doesn't really fit. If you want to have a leader key binding for `doom/escape`, `<leader> ESC` would probably be a better fit.

**Comment by hlissner** [comment]
Thanks for the suggestion (and sorry for the late response), but I don't intend to move `SPC g` to `SPC v`, or `SPC g g` to `SPC g v`, for these reasons:

1. The choice of `SPC g` was derived not from **g**it, per se, but from ma**g**it and because `magit` is bound to `C-x g` by default.
2. There is no Emacs convention that stipulates `g` keys are bound to abort commands, so I don't agree that it's more "Emacsy" to follow such a convention.
3. Binding repeat keys `SPC g g`, `SPC b b`, `SPC f f` is a Doom convention for invoking a prefix's "primary" function, and quickly. I don't plan to abandon this convention (to move `SPC g g` to `SPC g v`). The only exception are instances where a clear "primary" command does not exist.
4. `doom/escape` is already on `ESC` and `C-g`. I don't think it needs a leader key too.

In any case, thank you for the suggestion. There may be room to move `SPC g` to `SPC v` as the built-in vc.el's capabilities expand, however (it seems to be slowly encroaching on magit's territory in recent commits of 29), but that's something to consider when 29.1 has a stable release.
