### ISSUE TITLE
magit-forge has error when activating Forge with `@` key in git status buffer

### ISSUE THREAD

**Issue by TK-WF** [doomemacs/doomemacs#6343]
### What did you expect to happen?

I expected the Forge popup to appear with further key selections.

### What actually happened?

Receive an error in the mini-buffer: transient-setup: Wrong type argument: characterp, "\300\301!\207"

### Describe your attempts to resolve the issue

I've tried removing the `+forge` module flag and executing `doom sync` and restarting emacs, then re-adding the flag and going through the same sync/reload process.

Invoking Forge commands directly (e.g. via M-x or SPC leader sequence) work fine.

### Steps to reproduce

1. Configure init.el to activate magit +forge.
2. re-sync doom and restart emacs.
3. Open magit-status in an existing git repo.
4. type `@` to invoke Forge menu.

### System Information

https://pastebin.com/nUx0NWsR

**Comment by Kaylebor** [comment]
This error also happened to me, but I was also rebuilding `.elc` files from scratch, restarting Doom, etc... And now doesn't happen.
So I can't reproduce it anymore.

**Comment by agzam** [comment]
It's still happening on my machine. 

Emacs 29.0.50 --with-native-comp

I tried removing .elc files for magit, forge and transient, and that didn't fix it. Still can't figure out why it breaks.

**Comment by tarsius** [comment]
Try reinstalling transient, magit and forge, in that order. In an emacs instance in which none of these packages were available (so that we can really be sure that no old loaded code leaked into the compilation output of the new code).

Please `eval-buffer` `magit-transient.el` to get a more meaningful backtrace. (Based on that you might also be able to use some debug statements to learn more about where things start to go wrong.)

**Comment by TK-WF** [comment]
I finally got resolution to this issue by completely removing doom-emacs and reinstalling from scratch (with my custom configs intact).

My problems began when I upgraded to Emacs 28.1, so there must have been some crufty stuff leftover. YMMV
