### ISSUE TITLE
Support dirvish plugin in dired module

### ISSUE THREAD

**Issue by zrquan** [doomemacs/doomemacs#6397]
### Describe your request

After trying [dirvish](https://github.com/alexluigit/dirvish) briefly, I think its preview experience is better than ranger. Hope to add a `+dirvish` flag in dired module.

### Briefly explain its use-case

Replace ranger

Please visit https://github.com/alexluigit/dirvish

**Comment by zrquan** [comment]
> there looks to be a face highlighting the current line that isn’t themed properly

Maybe the same issue at alexluigit/dirvish#43, you can try to unpin the package or take the [author's workaround](https://github.com/alexluigit/dirvish/issues/43#issuecomment-1130068538), I will bump version of dirvish when I have a moment.

> It seems to intermittently crash Emacs when I attempt kill Dirvish buffers.

Sorry, I never encountered this problem 🤔

**Comment by alexluigit** [comment]
Hi, @hpfr.

> but it can crash Emacs

There is a bug related to `kill-buffer` in this commit that crashes Emacs, but it was [fixed](https://github.com/alexluigit/dirvish/commit/753f033801a06f090e56b18fd0da3c949cd6bc98) long ago.

> and window management is weird

What do you mean by weird? Did you mean the window layout is different from the screenshots? Like [this](https://github.com/alexluigit/dirvish/issues/18)? Or maybe you were trying to quit a fullscreen session with `kill-buffer`, which of course results in unwanted window layout, because `kill-buffer` won't restore the layout for you, you should use `quit-window` for that purpose.

> there looks to be a face highlighting the current line that isn’t themed properly

I'm not sure what you are referring to by saying "themed properly". If you don't like the color, you can customize the `dirvish-hl-line` face.

**Comment by alexluigit** [comment]
Hi, @zrquan. I noticed this PR the other day, thanks very much for submitting this.

Apart from bumping the version, I got a few suggestions for this: 
1. `fd-dired` may causes unwanted behaviors when use together with dirvish, so please disable this package and use `dirvish-fd` instead (see [demo](https://github.com/alexluigit/dirvish/blob/main/EXTENSIONS.org#fd-interface-in-dirvish-dirvish-fdel)).  
2. This [feature](https://github.com/doomemacs/doomemacs/blob/master/modules/emacs/dired/config.el#L75) should be replaced by the `vc-state` attributes
3. Like I mentioned in last comment, please inhibit the `+dired/quit-all` binding for this flag.
4. `dirvish-dispatch` provides useful guidance for newcomers of Dired/Dirvish, please consider giving it a keybinding. Maybe remap the `dired-summary` ("?" key by default) to this command.

See: https://github.com/alexluigit/dirvish/blob/main/CUSTOMIZING.org#working-with-doom-emacs
