### ISSUE TITLE
"The Agda mode’s version (2.6.3) does not match that of agda (2.6.2.1)" (Agda installed via Nix)

### ISSUE THREAD

**Issue by venus-as-a-boy** [doomemacs/doomemacs#6402]
### What did you expect to happen?

I'm trying to use the agda-mode package with agda installed via nix on macOS, and I can't seem to get it to start up.

### What actually happened?

I get the message "The Agda mode’s version (2.6.3) does not match that of agda (2.6.2.1)" when I try to run `agda2-restart`. I

### Describe your attempts to resolve the issue

I tried using `(agda +local)` per [this issue](https://github.com/doomemacs/doomemacs/issues/2547), but got the same result.

### Steps to reproduce

1. install agda via `nix -iA nixpkgs.agda`
2. load an agda file
3. run `agda-restart`

### System Information

https://pastebin.com/rHiLQ5Kw

**Comment by hlissner** [comment]
Using `(agda +local)` is the correct solution to this. This stops our module from installing any packages at all (and assumes you'll take care of that through your package manager---in this case, nix). The flag exists because version mismatches like these are common. 

If there are version mismatches despite `+local`, then the issue originates from the installation provided by your package manager, and is not anything Doom can do anything about. Remember to run to `doom sync` after installing agda via your package manager, if you haven't already--to make sure you don't have left-over autoloads from before you enabled `+local`. 

As this issue is unactionable I will close it, but feel free to follow up here.
