### ISSUE TITLE
Let doctor diagnose if `locate` is missing

### ISSUE THREAD

**Issue by anntnzrb** [doomemacs/doomemacs#6474]
### Describe your request

Allow the doc to notify if the `locate` binary is not found, I really thought this package was part of the utility set most (if not all) Linux Distributions shipped with. I noticed this when I tried using `consult-locate` (also `M-x locate`).

I would have loved to contribute with a doctor warn, but since this sounds like a `core` thing, didn't know it should go.

**Extra Info**: https://pastebin.com/r3Pqw0wP
**Resources**:  https://wiki.archlinux.org/title/locate

### Briefly explain its use-case

Whenever you run `doom doctor` it will notify the missing package so it can be installed.

**Comment by hlissner** [comment]
I understand the confusion, but I have to reject this suggestion. The trouble with packages like consult and counsel is that they offer completion commands for _many_ external programs. It'd be more overwhelming than helpful if the doctor complained about every one of them, since they're not a prerequisite for a working Doom environment, and don't pose a significant loss in Emacs performance or functionality if they're missing (and often, there are many alternatives present, like consult-fzf, consult-find, etc).

I think it's enough that `consult-locate` (and other commands) throw an error when the program they need is missing, as they do:

![image](https://user-images.githubusercontent.com/510883/174498080-2353a316-0817-415f-ab85-33b094e77647.png)

Perhaps the error message could be more informative, but that should be requested upstream.

In any case, thanks for bringing it to my attention. Perhaps I'll consider adding `--verbose` or `--level=N` options to `doom doctor`, then introducing more granular (and less important) tests to hide behind certain levels, but that would need more thought. I plan to rewrite the doctor system and its tests (as part of #4273), so I'll reconsider this once I get to that.
