### ISSUE TITLE
package! doesn't load, after doom sync -u

### ISSUE THREAD

**Issue by BuddhiLW** [doomemacs/doomemacs#6546]
### What did you expect to happen?

Doom load, normally, a package such as this,
```elisp
(package! impatient-mode
  :recipe (:host github :repo "skeeto/impatient-mode"))
```

### What actually happened?

At startup, I receive:
```elisp
Debugger entered--Lisp error: (void-function package!)
  (package! impatient-mode :recipe (:host github :repo "skeeto/impatient-mode"))
```

### Describe your attempts to resolve the issue

`package-install` everything by hand.

### Steps to reproduce

0. Have this snippet-config,
```elisp
(package! impatient-mode
  :recipe (:host github :repo "skeeto/impatient-mode"))
```
1. Open Emacs (with --debug-init)
2. get error on `package!` being a void-function

### System Information

https://pastebin.com/Sj0e72Cb

**Comment by hlissner** [comment]
You did not specify what file you put that `package!` statement in, but as `void-function package!` errors should only ever happen if you use them in the wrong place, I suspect you've put them in `$DOOMDIR/config.el` or `$DOOMDIR/init.el`, instead of `$DOOMDIR/packages.el`.

To quote `package!`'s docstring (accessible with `C-h f package\!`):

> Only use this macro in a module's packages.el file.

**Comment by BuddhiLW** [comment]
You are correct! I didn't know that you should only put packages there, using `package!`.
