### ISSUE TITLE
The dart-mode repository is gone

### ISSUE THREAD

**Issue by daraul** [doomemacs/doomemacs#6621]
### What did you expect to happen?

I expected doom to be installed

### What actually happened?

The installation fails when attempting to clone [dart-mode](https://github.com/bradyt/dart-mode).

### Describe your attempts to resolve the issue

Removing dart from my init.el file. This works, but do note that my system information doesn't mention dart since I removed it before creating this issue. 

### Steps to reproduce

Attempt to install doom from scratch with the dart plugin enabled. 

### System Information

https://pastebin.com/WnB95nbV

**Comment by hlissner** [comment]
For some reason bradyt/dart-mode was deleted. This has been reported [to MELPA](https://github.com/melpa/melpa/issues/8146). I expect it to be resolved upstream soon, otherwise I'll update the recipe to use a mirror.

-----

The workaround is to use [a mirror](https://github.com/emacsfodder/dart-mode). Override the `:lang dart` module's recipe for it, like so:

```elisp
;; in $DOOMDIR/packages.el
(package! dart-mode :recipe (:repo "emacsfodder/dart-mode"))
```

Then run `doom sync -u` and reboot Emacs.

**Comment by daraul** [comment]
Oh, your workaround is better -- thank you!

**Comment by hlissner** [comment]
[bradyt/dart-mode](https://github.com/bradyt/dart-mode) is back, it seems, so the workaround is no longer necessary.
