### ISSUE TITLE
all documentation and the subsequent links withing them are not working

### ISSUE THREAD

**Issue by onlyvip** [doomemacs/doomemacs#6671]
### What did you expect to happen?

when i try to go to any sub links from [here](https://github.com/doomemacs/doomemacs/blob/master/docs/index.org#getting-started) then its not working same goes for a new doom install, after opening the docs via SPC h d h, and then trying to go to sub documentation chapters their links are not working.

### What actually happened?

documentation hyperlinks/sublinks for subsequent doc files is not updated and not working on the repo as well inside doom.

### Describe your attempts to resolve the issue

none

### Steps to reproduce

go to documentation and try to click on any sub links in it.

### System Information

https://pastebin.com/QY1azd5W

**Comment by dschrempf** [comment]
In particular, the following documents were removed and show 404s:
 - `getting_started.org`
 - `workflow.org`
 - `modules.org`

Also the main README is linking to the missing `modules.org` file. There may be more missing links in the main README.

**Comment by jhodgdev** [comment]
Does anyone know which commit removed the docs?

**Comment by jhodgdev** [comment]
Docs can be found [here](https://github.com/doomemacs/doomemacs/tree/develop/docs) in the meanwhile.

**Comment by hlissner** [comment]
I'm that some docs are missing; I'm currently in the process of replacing them with new, rewritten ones, but it's taking more time than expected, as I'm also working on the v3 release of Doom, which brings about a lot of big changes, so I'm trying to make sure they all happen at once, rather than several times over a drawn out period. 

For the time being the old docs are available [on the develop branch](https://github.com/doomemacs/doomemacs/tree/develop/docs), as jhodgdev mentioned. That said, the module docs, in-repo, are up-to-date. You can get to them with `SPC h d m` (`M-x doom/help-modules`). 

I'll keep this open until the new docs are in place.

**Comment by dbechrd** [comment]
The readme on the landing page is completely broken as a result of this.. super confusing for new users like myself who are trying to click e.g. "Getting Started" links and learn how to install. Would be best to fix these links however possible in the meantime while new docs are being worked on, as nobody who lands on the readme is going to understand they need to switch to a different branch to read the installation instructions / getting started guide.

**Comment by gui-salome** [comment]
Also, some of the subsequent links in getting started point to the hlissner account.

**Comment by hlissner** [comment]
Sorry for the delay; life and distractions got in the way, so the new docs are taking longer than expected. I've restored the old files in 1f29b07 for the time being.
