### ISSUE TITLE
next location (C-i) not working in C-o and C-i pair

### ISSUE THREAD

**Issue by kujohn** [doomemacs/doomemacs#6714]
### What did you expect to happen?

`C-i` would goto next location

### What actually happened?

`C-i` adds indents to the current line

### Describe your attempts to resolve the issue

n/a

### Steps to reproduce

1. Open document
2. Try to jump around few lines
3. `C-o` will jump back to previous lines
4. `C-i` will insert indents

### System Information

https://pastebin.com/dznRwGsF

**Comment by hlissner** [comment]
Unfortunately, this is not an issue Doom can address, as it's an age-old characteristic of terminals, to interpret `C-i` as a `TAB`, which is what Emacs receive. An alternative keybind must be used, in this case, e.g. `C-M-,` -- or bind a new one, for example `g/`:

```elisp
(map! :n "g." #'better-jumper-jump-backward)
```

In GUI Emacs, Doom can and has [taught Emacs to distinguish the two input events](https://github.com/doomemacs/doomemacs/blob/master/lisp/doom-keybinds.el#L44-L57), but there's no way to do this for Emacs. Your best hope is to adopt a more modern terminal capable of remapping "TAB" to the correct event, but I'm not aware of one that exists.

Since there's nothing Doom can do here, I'll close this issue, but feel free to follow up here.

**Comment by miles170** [comment]
I wonder if we can bind `evil-jump-forward` to `TAB` when using emacs under a terminal.
The following code works for either a GUI or a terminal.

```elisp
(map! :m (if (display-graphic-p) [C-i] "TAB") #'evil-jump-forward)
```

**Comment by kujohn** [comment]
@miles170 thank you thank you. This is exactly what I was looking for. There's quiet a lot of muscle memory that's hard to unlearn.

**Comment by hlissner** [comment]
The keybind above will break `C-i` for daemon+gui users, and has the disasterous side-effect of overriding most other `TAB` keybinds in various modes. Use it with caution.

The keybind you likely want to unbind is [this one](https://github.com/doomemacs/doomemacs/blob/master/modules/config/default/+evil-bindings.el#L47-L69):

```elisp
(map! :m [tab] nil)
```
