### ISSUE TITLE
there is a bug on package "literate" 

### ISSUE THREAD

**Issue by pipiTan** [doomemacs/doomemacs#6717]
### What did you expect to happen?

doom sync and upgrade work normally.

### What actually happened?

doom sync and doom upgrade are broken if package literate is active.
<img width="538" alt="截屏2022-08-24 16 00 51" src="https://user-images.githubusercontent.com/18749923/186364569-b2fd53b6-d21f-41ea-9fa7-d005a1f8ceca.png">
<img width="567" alt="截屏2022-08-24 16 01 04" src="https://user-images.githubusercontent.com/18749923/186364582-0ccb71ad-aa61-406c-b8d3-a69eb0d24072.png">

### Describe your attempts to resolve the issue

commentting literate will work for me.

### Steps to reproduce

turn on package literate 

### System Information

https://pastebin.com/xcQX1Mhg

**Comment by elken** [comment]
Is there a valid config.org file in your doomdir?

**Comment by pipiTan** [comment]
> Is there a valid config.org file in your doomdir?

It seem that config.org is empty and I haven't do anything with config.org as well. Maybe it is valid.

**Comment by hlissner** [comment]
I suppose the problem here is that tangling "0 code blocks" is considered an error state (and perhaps erroneously assumed to be due to an invalid config.org, rather than an empty one). Since ob-tangle doesn't throw up catchable errors in any case, I'm not sure how best to deal with this yet.

For the time being, the quick fix is to insert at least one tanglable block in your config.org. Eg..

```elisp
#+begin_src emacs-lisp
;; Nothing here yet!
#+end_src
```

**Comment by elken** [comment]
> I suppose the problem here is that tangling "0 code blocks" is considered an error state (and perhaps erroneously assumed to be due to an invalid config.org, rather than an empty one). Since ob-tangle doesn't throw up catchable errors in any case, I'm not sure how best to deal with this yet.
> 
> For the time being, the quick fix is to insert at least one tanglable block in your config.org. E.g.
> 
> ```emacs-lisp
> #+begin_src emacs-lisp
> ;; Nothing here yet!
> #+end_src
> ```

I think in this case empty is also an error. If there's nothing to tangle it should be flagged to the user.

Maybe a separate pre-check to see if the file is genuinely empty?

**Comment by pipiTan** [comment]
@hlissner @elken It works! But I wonder why I didn't encounter this bug before?

**Comment by samyak039** [comment]
@pipiTan How did you get to know that the error was caused by `literate` package, I was also having the same issue, but couldn't get any understanding, even tried `doom sync -D`.

and the solution mentioned by @elken, doesn't works if you want to have your own `custom.el` file also, it there any other workaround except for copying the complete `custom.el` to `custom.org` ?

**Comment by hlissner** [comment]
As of 0d40532, tangling on `doom sync` should emit more informative error messages (and output, in general), which should help folks avoid issues like this in the future. Thanks for bringing it to my attention!
