### ISSUE TITLE
link broken in docs and I don't know how to fix it myself

### ISSUE THREAD

**Issue by rgkirch** [doomemacs/doomemacs#6763]
### What did you expect to happen?

In
https://github.com/doomemacs/doomemacs/blob/master/docs/getting_started.org#installing-packages
```
- Or the package really doesn't exist on ELPA, MELPA, or EmacsMirror and you'll
  need to [[*Installing packages from external sources][specify a recipe for it]].
```
`specify a recipe for it` should link to 
https://github.com/doomemacs/doomemacs/blob/master/docs/getting_started.org#installing-packages-from-external-sources

### What actually happened?

The link is broken.

### Describe your attempts to resolve the issue

Should it say `*** Installing...`?

### Steps to reproduce

I'd like to be able to fix any broken links that I find.

### System Information

Sorry if this just noise. I know there are lots of other issues.

**Comment by rgkirch** [comment]
The error says `The 'doomemacs/doomemacs' repository doesn't contain the 'docs/*Installing packages from external sources' path in 'master'.`

**Comment by rgkirch** [comment]
Omg, I just noticed that it's linking to the very next heading. 🤦

**Comment by elken** [comment]
It's not broken per-se, it's just primarily designed around being viewed in emacs.

**Comment by hlissner** [comment]
This is intentional. Our in-repo docs are designed to be read from within Emacs or online at https://docs.doomemacs.org (though I'm still working on updating that), not Github or any other forge/preview system. Unfortunately, many of these services have abysmal Org support, and supporting it has turned out to be a painful and unfruitful pursuit (our project README.md is the sole exception, and that's why it's in markdown).

Anyhow, I'll soon replace getting_started.org (and others) with a new manual, which will include a prominent warning about this, but for the time being, I will close this as this issue is unactionable otherwise. Thanks for bringing it to my attention, in any case!

**Comment by rgkirch** [comment]
Thank you for clearing that up.
