### ISSUE TITLE
Icons break on Emacs 28.2, Ubunto 20.04 after commit

### ISSUE THREAD

**Issue by MarcKaufmann** [doomemacs/doomemacs#6807]
### What did you expect to happen?

I updated Doom (last update probably in May 2022) and expected the icons to show up as before the update. I am on Ubuntu 20.04, Emacs 28.2.

### What actually happened?

When I updated Doom, the icons break, see screenshot.

![doom-screenshot](https://user-images.githubusercontent.com/756408/190893324-fc6bb413-9463-4f7a-9e13-48ff98ef77f1.png)

### Describe your attempts to resolve the issue

I posted a question on Discord, but didn't receive any answers yet (disclaimer: only half a day ago). 

In the meantime, I used git bisect to figure out which commit is the first to cause it. This suggests that it is commit 797866b59601f93647a8f9bca644ad5766a03978, icons show up properly for the commit before. Icons are still broken in the latest commit (195359cf993dbac00917e6ee9f3e77ede72de24a).

The way I tested it on each run is to:

- `rm -r ~/.doom.d/
- Install doom: `cd ~/.emacs.d && bin/doom install`, replying with 'yes' to installing the icon fonts
- Run `doom sync`, `doom doctor` which always showed that the fonts were loaded and didn't show any other issues
- `doom run` and check if the fonts looked OK

Thus I am not using my own config, but the vanilla Doom, as I remove `.doom.d/` each time.

### Steps to reproduce

I run Ubuntu 20.04, Emacs 28.2.

1. Checkout commit 797866b59601f93647a8f9bca644ad5766a03978
2. Do clean install
3. Run Doom, stare at the broken icons

### System Information

https://pastebin.com/tSpN9wTH

**Comment by hlissner** [comment]
I cannot reproduce this. Since this is the first time I've heard of it between https://github.com/doomemacs/doomemacs/commit/797866b59601f93647a8f9bca644ad5766a03978 and now (a whole three months), and that the vast majority of the time font problems are not Doom issues, I am inclined to suspect a local installation issue. Usually its the fonts. Sometimes its missing features in the Emacs build. Since you appear to have the right features, we can rule out the former.

To rule out Doom: try `doom env` then restart Emacs, in case a stale envvar is the culprit. Otherwise, double check that the fonts are truly installed on your system with `M-x all-the-icons-install-fonts`, or by downloading them directly from https://github.com/domtronn/all-the-icons.el/tree/master/fonts. Also check `fc-list` to make sure fontconfig sees them, and `~/.local/share/fonts/` to make sure the font files exist and aren't empty/corrupted.

**Comment by hlissner** [comment]
Oh hold on, are you launching Doom with `doom run`? In order for `doom run` to function, Doom must create a fake $HOME to house symlinks to your Emacs config, which naturally won't contain `$HOME/.local/share/fonts`. This is technical limitation of Emacs <=28, and `all-the-icons` is often the first casualty of this issue.

If this is the case, launching Doom normally (by running or launching `emacs` directly) should work as expected. `doom run` exists solely for testing and debugging, and shouldn't be relied on as a proper entry point into Doom. Some improvements to this will be made as part of #4273, but until a stable 29.x release comes out (which introduces a handy `--init-directory DIR` switch), there's not much Doom can do about this.

**Comment by hlissner** [comment]
As of 231fc9c, `doom run` now symlinks various XDG directories to the fake $HOME, which should hopefully resolve this issue, albeit temporary and likely to suffer other edge cases. It's likely our only option until 29 is stable (and we drop 28.x support). Let me know if the issue resurfaces and I'll reopen this. Thanks for bringing it to my attention!
