### ISSUE TITLE
Not clear how to install packages - is it package-install or (use-package!) or (use-package)or (package!)

### ISSUE THREAD

**Issue by danielkrajnik** [doomemacs/doomemacs#6817]
It takes me ages to install org-download - it doesn't load and I don't know what combination of the above functions were meant to install it.

An explanation whether ```package-install``` is supported or is **only** ```(package )``` meant for installing packages would be really useful. 

### System Information

https://pastebin.com/KSTcua3x

**Comment by hlissner** [comment]
Doom has its own package manager, [read about it in our documentation](https://github.com/doomemacs/doomemacs/blob/develop/docs/getting_started.org#package-management). TL;DR: add `(package! org-download)` to `~/.doom.d/packages.el`, then run `doom sync` to install packages.

Doom doesn't _stop_ you from using package.el, if you like (e.g. installing packages with `package-install` and `use-package`), but this is not set up for you out of the box (because it's redundant with our package manager; there's no reason to use it except personal preference). If it's what you prefer, you'll have to [initialize it yourself](https://medium.com/helpshift-engineering/configuring-emacs-from-scratch-packages-220bbc5e55b7) before it can be used, otherwise Emacs will "forget" the packages you've installed the next time you restart it.

Alternatively, activate Doom's `:lang org` module with the `+dragndrop` flag. This sets up `org-download` for you. Use `SPC h d m` (or `M-x doom/help-modules`) to look up docs on this module.

-----

Anyhow, as our issue form stated, our issue tracker is only for bug reports, not user support. Please post these to [our Discord](https://doomemacs.org/discord) or [Discourse](https://discourse.doomemacs.org) instead.
