### ISSUE TITLE
Doom CLI no longer works when Doom user directory is a symlink

### ISSUE THREAD

**Issue by pharcosyle** [doomemacs/doomemacs#6845]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

Doom CLI works.

### Current behavior

`doom sync`, `doom upgrade p`, probably others, throw an error. This only happens when my ~/.config/doom folder is a symlink, when it and the contents are regular files/directories everything works fine.

Full backtrace: https://pastebin.com/4QkJGpDx

This is caused by something newer than doomemacs/doomemacs@b7b66e620, possibly the introduction of `doom-context`.

I'm on Emacs 29 but I'm pretty sure it has nothing to do with that.

### Steps to reproduce

Above.

### System Information

https://pastebin.com/esryxSUs

**Comment by Trotter-Wiz-Kiwanis** [comment]
Can confirm with other files from `~/.doom.d`.

**Comment by hlissner** [comment]
I cannot reproduce this when $DOOMDIR is a symlink, but I can reproduce this when _the contents_ of $DOOMDIR are recursively symlinked, which is not supported and probably won't ever be, because there is no way to determine "the true parent directory" of an already-resolved symlink, and it's far too brittle (and expensive) a process to ensure our module API *always* receives unresolved file paths. 

I see you are using Nix and are recursively deploying Doom into your nix store, probably to avoid any file-writes to your $DOOMDIR throwing errors, so I suggest the following:

1. Don't recursively link $DOOMDIR,
2. Set `custom-file` to a location outside of $DOOMDIR from your config, e.g.

   ```elisp
   ;;; in $DOOMDIR/config.el
   (setq custom-file (expand-file-name "custom.el" doom-data-dir))
   ```

Since there is no other files that Doom (or Emacs) writes to $DOOMDIR, the recursive link is no longer required.

**Comment by hlissner** [comment]
Nevermind, turns out there was an edge case with module context resolution. As of b8038e9 (and 07171185bb56629623d003467c6228326d6c2259) this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by pharcosyle** [comment]
Yup works now, thank you!
