### ISSUE TITLE
Certain keybinds missing on Emacs 29

### ISSUE THREAD

**Issue by TomFryers** [doomemacs/doomemacs#6859]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [ ] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

All keybinds are available. For instance,<kbd>SPC</kbd> <kbd>p</kbd> <kbd>p</kbd> should open the list of projects.

### Current behavior

Some keybindings are missing (Evil ones?). This is a screenshot of the splash screen after pressing <kbd>SPC</kbd>. Two of the menu items have the wrong keybinding, and the menu at the bottom is missing things (e.g. `b`).
![home](https://user-images.githubusercontent.com/61272761/192894733-85960fa3-8c08-491d-85d9-5736924292ae.png)
Pressing <kbd>SPC</kbd> <kbd>p</kbd> <kbd>p</kbd> gives `SPC p p is undefined.`

Adding 
```elisp
(setq use-package-inject-hooks t)
```
to the start of `init.el` and
```elisp
 (defadvice! fixed-doom-module-list (fn &rest args)
    :around #'doom-module-list
    (nreverse (apply fn args)))
```
to the end makes the problem seem to disappear.

This is similar to #6813.

### Steps to reproduce

1. Open Emacs (master, f6fb2b9e1).
2. Observe `C-c p p` instead of `SPC p p` on the splash screen.

### System Information

https://pastebin.com/tFdL8uJu

**Comment by hlissner** [comment]
Is your `M-x doom/info` from before or after you added the `fixed-doom-module-list` fix to your config?

**Comment by agzam** [comment]
I have the same problem, except the listed workarounds don't work for me.
I have to say, these few days were extremely disappointing for me. I use Emacs 29 with --native-comp. It takes a while to build it. It seems I can no longer go back to 28, because I'm already utilizing things that don't exist in 28. 
I don't even use too many Doom modules, mostly my own. I have built an extensive configuration using Doom's core and macros. I am extremely happy with it. I lost two days of work trying to find a workaround and I still don't understand the underlying issue. It looks like I have no other option but to roll a few days back. And live without updating Doom until the issue(s) get fixed.

**Comment by TomFryers** [comment]
That's without the workaround. With the `fixed-doom-module-list` fix, it's [this](https://pastebin.com/dRLxAy0c), which seems just to have the module list reversed.

**Comment by TomFryers** [comment]
After re-installing Doom, the workaround no longer works (but neither do the keybindings).

**Comment by hlissner** [comment]
> I have to say these few days were highly disappointing for me. I use Emacs 29 with --native-comp. It takes a while to build it. It seems I can no longer go back to 28 because I'm already utilizing things that don't exist in 28.

@agzam I'm afraid it's something you should get used to, if you intend to live on the bleeding edge of Emacs. I'm sorry if I've said this to you before (on Github, Discourse, or Discord), but this is something all Emacs 29 users should hear at least once, so it bears repeating: 

I **highly** recommend you downgrade to 28.x if you don't want to deal with these problems as often as you're going to. Otherwise, find a commit of Emacs 29 that works for you and *never* upgrade until it gets a stable release next year. Every update will be a toin coss if you don't. 

Side note: how many of Doom's modules you use won't matter. Our modules rely little on upstream Emacs and more on third party packages, whose installed versions we can control (through pinning). What Doom cannot control is what version of Emacs you use it on, so Doom's core is most sensitive to changes in Emacs.

> That's without the workaround. With the fixed-doom-module-list fix, it's [this](https://pastebin.com/dRLxAy0c), which seems just to have the module list reversed.

@TomFryers Your module list looks correct without the fix. As I suspected, the workaround is just masking your issue, not fixing it.

> (setq use-package-inject-hooks t)

@TomFryers I have no idea why this should fix your issue. It has nothing to do with Doom. Is your private config up somewhere I can see it?

**Comment by hlissner** [comment]
@TomFryers Nevermind. I updated to a newer version of 29 and am now able to reproduce the issue. Seems a _new_ and frustratingly similiar issue snuck into 29 while I was debugging https://github.com/doomemacs/doomemacs/issues/6813. I'll look into this further.

**Comment by TomFryers** [comment]
`(setq use-package-inject-hooks t)` doesn't help any more. It seemed previously to be required to stop the workaround causing a crash, but after re-installing Doom, the workaround now always causes
```elisp
Unexpected error in Doom's core: /home/tom/.emacs.d/lisp/doom-keybinds.el, (void-function use-package!)
```
Maybe there was some stale generated thing somewhere (although I did run `doom sync` a lot).

**Comment by hlissner** [comment]
As it turns out, this _was_ caused by #6813. As of 285b460 this issue should finally be fixed. Let me know if that doesn't fix your issue and I'll reopen it.

**Comment by TomFryers** [comment]
Seems to be fixed for me now. Thanks!

**Comment by hlissner** [comment]
@agzam Oh, I hadn't put two and two together and realized you are `Ag` on Discord. Must be the third time I've spammed that 29 disclaimer at you. Sorry about that! Btw, this might help folks like 29: <https://discourse.doomemacs.org/t/emacs-29-0-50-support/3241>

**Comment by agzam** [comment]
> Must be the third time I've spammed that 29

Haha, no worries. I know your position on Emacs 29, and you know mine. I've been using Doom on 29 for many months and this was literally the very first major plumbing catastrophe I had to deal with - I felt like my bathroom just blown up. But even that didn't convince me - I probably still end up moving to 29 again :)

I know, this stance takes away every right for me to complain when something breaks again. But I hope I learned my lesson - things don't always "magically" get fixed instantly, and sometimes the workaround is not so simple to find.

I'm not so scared of something else breaking so badly again. Right now, I'm scared to find out that Mitsuharu's port installed --with-mac-metal flag would feel snappier. Right now I can't tell, but moving back to 29 may give me that impression. That would mean that I'd have to choose between 29 and slightly faster working mac-port. That's a friggin' dilemma. The potential issues of Doom on 29 that you're talking about... are pistachios.
