### ISSUE TITLE
invisible text with mu4e and leuven theme

### ISSUE THREAD

**Issue by tillydray** [doomemacs/doomemacs#7010]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When I open mu4e (`SPC o m`) and see the dashboard, the shortcut keys are visible when using the leuven theme.

### Current behavior

When I open mu4e (`SPC o m`) and see the dashboard, the shortcut keys are the same color as the background, making them invisible.

There are no errors, etc. This does not occur on Vanilla Emacs

### Steps to reproduce

1. Open Emacs
2. Set theme to Leuven (`SPC h t leuven`)
3. Open mu4e (`SPC o m`)
4. See that the shortcut keys are white, making them invisible
5. Set theme to anything else (`SPC h t ENTER`)
6. See that the shortcut keys are visible

### System Information

https://pastebin.com/59KbTS3k

**Comment by undergroundquizscene** [comment]
I believe the problem here is that [+mu4e~main-action-str-prettier-a](https://github.com/doomemacs/doomemacs/blob/d5ccac5d71c819035fa251f01d023b3f94b4fba4/modules/email/mu4e/autoload/advice.el#L4) uses the wrong faces `(mode-line-emphasis bold)` instead of `mu4e-highlight-face`. I’m not sure why it does this, exactly: the function appears to be a copy of [mu4e--main-action-string](https://github.com/djcb/mu/blob/c5e0faea40408cc92e032704ddeb569b1cd6a8d2/mu4e/mu4e-main.el#L126) with some tweaks (such as using unicode for the bullets), but the face tweak is surprising.

Changing it back to mu4e-highlight-face fixes the problem for me – would that be an acceptable change?
