### ISSUE TITLE
Doom shell ignores system $PATH

### ISSUE THREAD

**Issue by dluksza** [doomemacs/doomemacs#7230]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behaviour

`M-! echo $PATH` prints the same value as `echo $PATH` in the terminal.

### Current behaviour

`M-! echo $PATH` prints:
```
/Users/lock/usr/bin:/bin:/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin:/usr/games:/usr/NX/bin
```
whereas `M-: (getenv "PATH")` prints:
```
"/Users/lock/.sdkman/candidates/java/current/bin:/Users/lock/.gem/bin:/Users/lock/.mix/escripts:/Users/lock/.config/emacs/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/lock/fvm/default/bin:/Users/lock/.pub-cache/bin"
```

This happens on Mac with `/opt/homebrew/zsh` set as shell and oh-my-zsh configs, with the latest Doom and `emacs-plus` from Homebrew.

I've tried running `doom env` and `doom sync` without any effect. Also tried adding `exec-path-from-shell` and initializing it in `config.el` which didn't help.

### Steps to reproduce

1. Open emacs
2. Press `M-!`
3. Type `echo $PATH`
4. Observe that returned value is different from the system `PATH`

### System Information

https://pastebin.com/JMLDM9dh

**Comment by myrgy** [comment]
Hi @dluksza 

I believe you system uses systemd, in that case you bash profile settings are not applied system-wide.

I would guess if you run emacs from terminal it should echo expected PATH.

You should either check you Desktop Environment settings or use systemd

**Comment by dluksza** [comment]
Hi @myrgy,

I'm on Mac OS and as far as I know, it doesn't use systemd.

The `emacs-plus` formula from Homebrew has a service that starts Emacs daemon. I did stopped that service (and verify that there is no daemon in the process list). Then started `emacs` from a terminal and it *still* prints the wrong `PATH` in the emacs shell as reported in the issue.

**Comment by BuddhiLW** [comment]
What happens if you shell is `bash`? 

You can change your shell by using `chsh` (_change shell_).

Maybe it's related to the PATH in `zsh` (e.i., the terminal emulator), or your underneath OS system mannger (systemd, runit etc.), nothing to do with DOOM, per se. Why? because both of these two pieces of software can change behavior related to configs and paths [^1][^2]. I used zsh for a while, but not really and expert.

Would be helpful to see all the places (that you have to figure out by yourself, unfortunately) in which your `.config` and `.local` action happens, inclusing `.zshrc` that could be or could not be in your `.config` etc. Give a look a the first resource to understand how zsh can change **PATH** behavior.

I can't reproduce the mistake with Ubuntu, running _systemd_, and _bash_. The order of the echo output-path is different, nothing more, in my case.

**Please post your OS system manager,** or the specific OS version you are running so I can search it. As the quote for systemd says[^2], system managers can alter very deeply configs systems on start. Therefore that is an essential part of the puzzle.

#### RESOURCES:
[^1]: [https://superuser.com/a/1776947/1422873](https://superuser.com/a/1776947/1422873)
[^2]: [systemd is a software suite that provides an array of system components for Linux operating systems. Its main aim is to **unify service configuration and behavior** across Linux distributions; systemd's primary component is a "system and service manager"—an init system used to **bootstrap user space** and manage user processes](https://systemd.io/)

**Comment by BuddhiLW** [comment]
One more thing, this may solve your problem; git it a read:

From search of "**how emacs get the configs in path**"[^1]:

```elisp
(defun set-exec-path-from-shell-PATH ()
  "Set up Emacs' `exec-path' and PATH environment variable to match
that used by the user's shell.

This is particularly useful under Mac OS X and macOS, where GUI
apps are not started from a shell."
  (interactive)
  (let ((path-from-shell (replace-regexp-in-string
			  "[ \t\n]*$" "" (shell-command-to-string
					  "$SHELL --login -c 'echo $PATH'"
						    ))))
    (setenv "PATH" path-from-shell)
    (setq exec-path (split-string path-from-shell path-separator))))

(set-exec-path-from-shell-PATH)
```

#### Resource:
[^1]: [https://www.emacswiki.org/emacs/ExecPath](https://www.emacswiki.org/emacs/ExecPath)

**Comment by dluksza** [comment]
After digging deeper into this and grepping for `/usr/NX/bin` in my home directory, I've found an old `.zshenv` that was messing with the `PATH` variable. Removing it has solved the problem.
