### ISSUE TITLE
Triggering `flycheck-popup-tip` clears the selected region

### ISSUE THREAD

**Issue by hartikainen** [doomemacs/doomemacs#7242]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

With `eglot` enabled, when I set mark and move the cursor within a buffer, I would expected the region to stay active and expand/shrink based on my cursors position. Here's an example of the expected behavior, *without* `eglot`, that is, otherwise the same setup as the current behavior below, but recorded after `eglot-shutdown`.

https://github.com/doomemacs/doomemacs/assets/2308543/82c8b105-31d2-4c2a-abb9-b7e4851c8a0c

### Current behavior

With `eglot` enabled, when the cursor moves onto a line with `eglot` error, the region gets cleared/unselected. See the video below. The region selection works as expected on the first couple of lines, but when I move the cursor to a region where `eglot` reports an error, the region suddenly disappears. 

https://github.com/doomemacs/doomemacs/assets/2308543/b4121313-837e-45ad-8157-88ae309cbd73

### Steps to reproduce

1. Open emacs with `(lsp +eglot)` and `(python +lsp +pyright +conda +cython)` configurations in `init.el`.
2. Write a python file with syntax error, similar to the example in the videos above.
3. Open the python file in a new buffer and make sure that `eglot` is enabled.
4. Set mark in the buffer.
5. Move cursor over to a point where `eglot` reports an error.
6. The region gets cleared.

### System Information

https://pastebin.com/EMjHtP6w

**Comment by totallyuniquelily** [comment]
I've run into what I believe to be this issue, and it can be triggered without eglot (though if it turns out to just be similar I'll open a new issue).
Posting this in the hope that a possibly more minimal repro is useful.

I have eglot disabled, but I lose my region in elisp scratch buffers when I move my cursor over an error.
Disabling `flycheck-mode` fixes it for me (though that might just be because there's no errors)

I've managed to reproduce with only the following:
1. disabled all modules aside from `emacs-lisp`, `syntax`, and `(default +bindings +smartparens))` and doom{,-dashboard,-quit}
2. Open a new scratch buffer, and set `emacs-lisp-mode`
3. Write code. It can be correct, as flycheck will whine about there being no heading or footer.
4. Same as in original report, set mark and move over an error.
    You may also press shift-down while on a line with an error, and that line will not be selected

https://github.com/doomemacs/doomemacs/assets/34397452/ec6c6e75-3669-42ec-926a-7f0eb67d0943

my `doom info`:
- with stripped down modules (as listed above): https://pastebin.com/s9YAG9vv
- with my usual config (just in case) https://pastebin.com/AAPFUrTh

**Comment by hlissner** [comment]
This is probably `flycheck-popup-tip`'s doing. See if enabling the `+childframe` flag on the `:checkers syntax` module fixes this for you (it'll use a child frame to display those errors instead).

**Comment by totallyuniquelily** [comment]
can indeed confirm that `+childframe` fixes it!

**Comment by hlissner** [comment]
As of 6756911 this should be resolved for folks not using `+childframe`. Thanks for bringing it to my attention!
