### ISSUE TITLE
Request to bump Magit version to at least 1d4bf64 ("magit-insert-remote-branches: Fix Git 2.40 compatibility")

### ISSUE THREAD

**Issue by prati0100** [doomemacs/doomemacs#7277]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When I hit `y r` in magit, it should list all remotes and their branches. But upstream magit had a bug that caused it to not work with Git v2.40 and above. This was fixed in commit 1d4bf64 ("magit-insert-remote-branches: Fix Git 2.40 compatibility") [0]. I see that currently Magit is pinned at commit 97a95f70079b6613bf98d2306279d3e03fe51234 [1].

Please bump Magit version to something after this commit so I can continue using it with Git v2.40 and above.

[0] https://github.com/magit/magit/commit/1d4bf64f33abbc5602d94986ea41706e4f166722
[1] https://github.com/doomemacs/doomemacs/blob/master/modules/tools/magit/packages.el#L4

### Current behavior

Magit throws the error:

```
cl--assertion-failed: Assertion failed: (equal branch (concat remote "/HEAD"))
```

### Steps to reproduce

Open Magit and then press `y r`.

### System Information

https://pastebin.com/HN8WP7Rf

**Comment by rallyemax** [comment]
I second bumping Magit, but kindly request that it be bumped to at least https://github.com/magit/magit/commit/2c2b34d7ac8a595be68702e53ff6f77755bfcd52, which also fixes a [bug](https://github.com/magit/magit/issues/4966) where WIP mode wouldn't work over TRAMP connections. This bug was referenced on the Doom Discourse [here](https://discourse.doomemacs.org/t/magit-wip-mode-not-working-over-tramp/4019/3)

I would take a crack at a PR myself, but the `magit` package recipe is a little complicated at the moment and I'm sure I would trigger some sort of subtle regression.
