### ISSUE TITLE
Viewing themes on-the-fly not working or disabled

### ISSUE THREAD

**Issue by BuddhiLW** [doomemacs/doomemacs#7308]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

`M-x load-theme` enabling on-the-fly changes of themes.

### Current behavior

Themes don't change on-the-fly

### Steps to reproduce

1. Open Emacs
2. `M-x load-theme` (SPC h t)
3. Navigate through options
4. Theme doesn't change

### System Information

https://pastebin.com/RqpzYtDK

**Comment by hlissner** [comment]
You seem to have both `:completion ivy` and `:completion vertico` enabled at the same time, which are not compatible with each other. This means that you have `counsel-theme` bound to `SPC h t`, which requires you press `C-SPC` to preview the selected theme.

If you disable the ivy module, `SPC h t` will be bound to `consult-theme`, which *does* auto preview themes.

In any case, I'll close this since this isn't a bug.
