### ISSUE TITLE
Doom Emacs stuck after installing and when listing, refreshing or installing packages

### ISSUE THREAD

**Issue by gauthamrdy** [doomemacs/doomemacs#7335]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When I list/install/refresh packages, it should list/install/refresh packages.

### Current behavior

Doom Emacs is stuck when I M-x and try to install/list/refresh packages.

### Steps to reproduce

1. Start Doom (Emacs 28.1)
2. M-x: package-install/list-packages/package-install, press ENTER
3. doom is stuck with the following text in the image attached. 
![Screenshot from 2023-08-03 16-17-55](https://github.com/doomemacs/doomemacs/assets/31089576/d6911e35-da3b-4b49-bb29-9b4b377559a2)

### System Information

https://gist.github.com/gauthamrdy/c62c191e650321f97f1e90be3b880b97

**Comment by Jdogzz** [comment]
I'm not able to reproduce this with at minimum `M-x list-packages`, and I have no issue installing packages the doom emacs way: https://github.com/doomemacs/doomemacs/blob/master/docs/getting_started.org#installing-packages

Are you still getting this error for `M-x list-packages`? And are you able to install an example package the doom emacs way as discussed in the above link? If so, would you please paste the output of `doom doctor`?

**Comment by hlissner** [comment]
The text shown in the minibuffer in OP's screenshot is not an error, it's a notification that a TLS connection succeeded (presumably while running `package-refresh-contents`), so I don't see what the issue is. `package.el` and Doom appear to be working as expected. Perhaps the problem is that the screen is frozen? If so, this likely has something to do with issues with our `inhibit-redisplay` setting during startup, which has been fixed and tweaked a number of times since this issue was initially posted, so updating Doom should address that problem.

Besides that, and because Doom doesn't use `package.el` at all, there is nothing here to fix. You must initialize package.el yourself if you really want to use it, by calling `(package-initialize)` somewhere in your config and doing all your package operations afterwards. There is no benefit to using package.el over Doom's package manager, besides the familiar interface (if you're a long time Emacs user) -- or perhaps for quickly installing packages to test them on-the-fly, but that's about it.

Thanks for bringing it to my attention, in any case.
