### ISSUE TITLE
duplicate `magit` import causing (un)pin issues

### ISSUE THREAD

**Issue by thejan2009** [doomemacs/doomemacs#7363]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

`(unpin! magit)` should unpin magit package.

### Current behavior

The `magit` and `git-commit` `package!`s at https://github.com/doomemacs/doomemacs/blob/master/modules/tools/magit/packages.el#L4 and https://github.com/doomemacs/doomemacs/blob/master/modules/emacs/vc/packages.el#L9 refer to the same dependency. To unpin/pin `magit` or `git-commit`, both packages need to be pinned at the same time.

### Steps to reproduce

`(unpin! magit)` then `doom sync -u` and verify the imported version.

### System Information

not needed

**Comment by michalrus** [comment]
I see it as well, after a clean `doom install`, Magit is pinned to a half-year old https://github.com/magit/magit/commit/97a95f70079b6613bf98d2306279d3e03fe51234 because of [the conflicting pin of `git-commit`](https://github.com/doomemacs/doomemacs/blob/7a7503045850ea83f205de6e71e6d886187f4a22/modules/emacs/vc/packages.el#L9C28-L9C68).

Causes: https://github.com/magit/magit/issues/4994
