### ISSUE TITLE
New checkout of doom is broken with Emacs 28.1

### ISSUE THREAD

**Issue by wilhelmy** [doomemacs/doomemacs#7555]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

After no response to my previous ticket #7539 I purged `~/.emacs.d`, re-cloned doom and ran `doom install`.

Expected behaviour is that doom would start up normally.

### Current behavior

Instead, emacs would start up with a glitchy window and doom not working. After an upgrade to Emacs 30.0.50 from git everything works.

### Steps to reproduce

Install Emacs 28.1, attempt to run doom.

### System Information

xx

**Comment by hlissner** [comment]
**:warning: This issue was closed and marked for deletion for the checked reasons below:**

+ [X] Issue cannot be acted on or investigated further because:
  + [X] Could not be reproduced in vanilla Doom on any of our test environments.
  + [X] Not enough information to act on.
  + [X] Vital information was omitted or inaccessible.
  + [X] Explanations are too vague or issue is too open ended.
  + [ ] It's unclear what you are trying to say.
+ [X] The following possibilities are more likely explanations and haven't been ruled out:
  + [ ] A pilot error.
  + [X] Private configuration.
  + [ ] A third-party package is behaving correctly, but in a manner you're not expecting.
  + [ ] A corrupt or broken Emacs installation.
  + [ ] Your system environment (hardware issues, the OS, shell environment, missing system dependencies, etc).

**This ruling is not absolute and _can be reversed_** if you follow up with enough information to further investigate this issue. Our [How to Debug Issues](https://discourse.doomemacs.org/how2debug) guide can help you find out more about it.

If you still feel lost after reading our debugging guide, raise your issue on our [Discord](https://doomemacs.org/discord) or [Discourse](https://discourse.doomemacs.org) -- there may be others who have experienced it. Otherwise, this issue will be automatically deleted after 14 days.

-----
> I apologize if this is inconvenient or you feel lost, but it takes a lot of time to review issues by myself. The complexity and extensibility of Emacs tends to produce a lot of false positive or open ended bug reports, so we will close issues that are <strong>unactionable</strong>, <strong>poorly explained (or undecipherable)</strong>, or <strong>not reproducible in vanilla Doom</strong>.
