### ISSUE TITLE
Can't save epa encrypted org .gpg file

### ISSUE THREAD

**Issue by rhysday** [doomemacs/doomemacs#7589]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Current behavior

Buffer freezes when I try to save my .gpg org file. Have to force close Emacs.

### System Information

https://pastebin.com/neFc7NZT

**Comment by rhysday** [comment]
Have had no problems with this org file for the last few years. Only started playing up after I ran Doom update a few weeks ago.

**Comment by rhysday** [comment]
Debug-on-quit log:
https://pastebin.com/t8PwqY50

**Comment by luogni** [comment]
Hi! I had the same issue. I found https://dev.gnupg.org/T6481. Yesterday I also updated Arch Linux and I saw that the gnupg package was upgraded to 2.4.3. If I revert back to older 2.2 package the issue goes away. It can be a temporary solution for you.

**Comment by rhysday** [comment]
> Hi! I had the same issue. I found https://dev.gnupg.org/T6481. Yesterday I also updated Arch Linux and I saw that the gnupg package was upgraded to 2.4.3. If I revert back to older 2.2 package the issue goes away. It can be a temporary solution for you.

Aah, downgrading gnupg worked. Thanks man

**Comment by FrederickGeek8** [comment]
This could be completely unrelated., but I was having a problem with `find-file` on macOS. As near as I can tell, it was related to `gnupg@2.4.3`. 

I posted about my problem on #7289, which dealt with an issue where people couldn't open files. They didn't post much debug information, so it's hard to tell if it was the same issue I was having.

The issue was apparently that the command `/usr/local/bin/gpg --with-colons --no-greeting --batch --with-fingerprint --with-fingerprint --fixed-list-mode --list-keys "Frederick"` was hanging indefinitely. **Downgrading to `gnupg@2.2` solved the issue immediately**. 

In my quest to fix this issue I noticed something before my downgrade:
- When I tried to run the above command the first time, `gpg` would get stuck waiting for a lock. I also noticed that I had at least a dozen `gpg` command that were stuck in the background. A quick `killall gpg` killed them. I then deleted the `~/.gnupg/gnupg_spawn_keyboxd_sentinel.lock` lock file, and the `gpg` command would hang without a message.

From there I downgraded to `gpupg@2.2`. Around that time, I noticed there was a `~/.gnupg/public-keys.d/pubring.db.lock` file. I didn't delete it before downgrading, but when I downgraded to `gnupg@2.2` everything worked great.

So I thought: what if I upgraded back to 2.4.3 and deleted that lockfile? So I did. And it worked! 

I'm wondering if there was a change that made `gnupg` respect that lockfile, since `gnupg@2.2` didn't seem to care, but 2.4.3 did. 

I posted my solution to this StackExchange post for someone macOS whose `gnupg` 2.4.3 started hanging a few days ago. I'm curious whether an unexpected poweroff may have locked up your `gnupg` 2.4.3.

https://unix.stackexchange.com/questions/766275/gpg-hangs-on-macos/766998#766998

Cheers!

Perhaps it's all unrelated. Maybe I'm drawing connections between two maybe issues that seem related. Nonetheless, I thought I would share my findings.

**Comment by shkodm** [comment]
@FrederickGeek8 thanks for your comment, I solved my issue already previously, and it was indeed related to new `gnupg`, version, but I had not realised it was realised it was related to the lock file. And good thing to have it all documented, I spent too much time debugging it.

**Comment by dorneanu** [comment]
I had exactly the same issue (on Arch Linux with Emacs 29.1.x). During some `pacman -Syu` gnupg got upgraded to 2.4 Downgrading it to 2.2.x solved the problem (it took me more than 2 hours to find the culprit).

**Comment by bleggett** [comment]
> This could be completely unrelated., but I was having a problem with `find-file` on macOS. As near as I can tell, it was related to `gnupg@2.4.3`.
> 
> I posted about my problem on #7289, which dealt with an issue where people couldn't open files. They didn't post much debug information, so it's hard to tell if it was the same issue I was having.
> 
> The issue was apparently that the command `/usr/local/bin/gpg --with-colons --no-greeting --batch --with-fingerprint --with-fingerprint --fixed-list-mode --list-keys "Frederick"` was hanging indefinitely. **Downgrading to `gnupg@2.2` solved the issue immediately**.
> 
> In my quest to fix this issue I noticed something before my downgrade:
> 
>     * When I tried to run the above command the first time, `gpg` would get stuck waiting for a lock. I also noticed that I had at least a dozen `gpg` command that were stuck in the background. A quick `killall gpg` killed them. I then deleted the `~/.gnupg/gnupg_spawn_keyboxd_sentinel.lock` lock file, and the `gpg` command would hang without a message.
> 
> 
> From there I downgraded to `gpupg@2.2`. Around that time, I noticed there was a `~/.gnupg/public-keys.d/pubring.db.lock` file. I didn't delete it before downgrading, but when I downgraded to `gnupg@2.2` everything worked great.
> 
> So I thought: what if I upgraded back to 2.4.3 and deleted that lockfile? So I did. And it worked!
> 
> I'm wondering if there was a change that made `gnupg` respect that lockfile, since `gnupg@2.2` didn't seem to care, but 2.4.3 did.
> 
> I posted my solution to this StackExchange post for someone macOS whose `gnupg` 2.4.3 started hanging a few days ago. I'm curious whether an unexpected poweroff may have locked up your `gnupg` 2.4.3.
> 
> https://unix.stackexchange.com/questions/766275/gpg-hangs-on-macos/766998#766998
> 
> Cheers!
> 
> Perhaps it's all unrelated. Maybe I'm drawing connections between two maybe issues that seem related. Nonetheless, I thought I would share my findings.

Had this exact issue on Fedora. Deleting the pubring lock fixed it.  TYVM for posting your fix, was driving me nuts.

**Comment by hlissner** [comment]
The issue has apparently been fixed in GnuPG 2.4.4, so updating fixes the issue.
