### ISSUE TITLE
Unable to run doom installation on M2 mac (Error: a subcommand is required)

### ISSUE THREAD

**Issue by atylermorgan** [doomemacs/doomemacs#7608]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Install doom on M2 mac via `~/.emacs.d/bin/doom install`

### Current behavior
Unable to install doom. All doom commands (other than help) produce the following error:
```~/.emacs.d/bin/doom install
Error: a subcommand is required

Available commands:


See 'doom h[elp] install' or 'doom install {-?,--help}' for documentation.
```

### Steps to reproduce

1. Install `emacs-plus`:
```brew install git ripgrep
brew install coreutils fd
xcode-select --install
brew tap d12frosted/emacs-plus
brew install emacs-plus
ln -s /opt/homebrew/opt/emacs-plus/Emacs.app /Applications
```

2. Download and install doom:
```rm -rf ~/.emacs.d
git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
~/.emacs.d/bin/doom install
```

### System Information

Doom info is unavailable, as it produces the same error as installation.
System is a Mac mini with M2 Pro chip, running Ventura 13.6.3

**Comment by atylermorgan** [comment]
Adding more info:
I have another computer (Macbook Air with M2 chip, running Ventura 13.6.3) where the above error does not occur. Today I re-downloaded and installed emacs-plus and doom without any issues. As far as I can tell, the only difference in the two machines is the M2 Pro chip. Has this been observed before?

**Comment by atylermorgan** [comment]
Adding more info:
I am able to run `doom install` if I clone the doom dev branch:

```git clone --branch develop https://github.com/hlissner/doom-emacs ~/.emacs.d```

However, after installation, I get an `init.el` error upon starting emacs:

```
Warning (initialization): An error occurred while loading ‘/Users/user01/.emacs.d/init.el’:

Symbol's function definition is void: string-remove-suffix

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

**Comment by BlameTroi** [comment]
Just a note that I just installed per the instructions on my M2 air without any problems other than a bad ln in the documentation (will create a new issue for that if needed. the ln -s in @atylermorgan report is correct).

**Comment by hlissner** [comment]
> Symbol's function definition is void: string-remove-suffix

This suggests to me that you might be launching the wrong version of Emacs. This function was introduced in Emacs 24.x, and the Emacs that comes bundled with MacOS (iirc) is older than that.

If not launching it with the wrong version of Emacs, you could be running `doom install` with the wrong Emacs executable in your `$PATH`. Run `which emacs` to check that. You can tell the doom script to use a specific Emacs executable by setting the `EMACS` envvar, e.g.

```sh
$ EMACS=/where/emacs/lives/ doom install
```

-----

As for the original `a subcommand is required` error, are you still seeing that? I haven't been able to reproduce this.

**Comment by bpizzi** [comment]
@hlissner Thanks to having looked into it ;)

I, too, have this problem.
I've not been able to resolve it using the `EMACS` envvar: to the best of my knownledge, I'm pretty sure I've got only one emacs installed on my system (Archlinux).

Here is what I gathered:

```
~ > uname -a
Linux [redacted] 6.7.3-arch1-2 #1 SMP PREEMPT_DYNAMIC Fri, 02 Feb 2024 17:03:55 +0000 x86_64 GNU/Linux

~ > sudo pacman -R emacs
checking dependencies...

Packages (1) emacs-29.2-1

Total Removed Size:  120.73 MiB

:: Do you want to remove these packages? [Y/n] y
[...]
(5/5) Updating the desktop file MIME type cache...

~ > which emacs
emacs not found

~ > emacs --version
zsh: command not found: emacs

~ > _ pacman -S emacs
resolving dependencies...
looking for conflicting packages...

Packages (1) emacs-29.2-1

Total Installed Size:  120.73 MiB

:: Proceed with installation? [Y/n] y
[...]
(6/6) Updating the desktop file MIME type cache...

~ > git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs
Cloning into '/home/[redacted]/.config/emacs'...
remote: Enumerating objects: 1162, done.
remote: Counting objects: 100% (1162/1162), done.
remote: Compressing objects: 100% (1046/1046), done.
remote: Total 1162 (delta 90), reused 529 (delta 74), pack-reused 0
Receiving objects: 100% (1162/1162), 1.14 MiB | 5.25 MiB/s, done.
Resolving deltas: 100% (90/90), done.

~ > sudo pacman -S emacs
resolving dependencies...
looking for conflicting packages...

Packages (4) libotf-0.9.16-4  m17n-db-1.8.5-1  m17n-lib-1.8.4-2  emacs-29.2-1

Total Installed Size:  128.49 MiB

:: Proceed with installation? [Y/n] y
[...]
(6/6) Updating the desktop file MIME type cache...

~ > emacs --version
GNU Emacs 29.2

~ > which emacs
/usr/bin/emacs

~ > cd .config/emacs

> ./bin/doom
Error: a subcommand is required

Available commands:
  help         Show documentation for a Doom CLI command.

  Config Management:
    sync       Commands for maintaining your Doom Emacs configuration.
    profiles   Commands for maintaining your Doom Emacs configuration.
    upgrade    Commands for maintaining your Doom Emacs configuration.
    env        Commands for maintaining your Doom Emacs configuration.
    build      Commands for maintaining your Doom Emacs configuration.
    install    Commands for maintaining your Doom Emacs configuration.
    compile    Commands for maintaining your Doom Emacs configuration.
    clean      Commands for maintaining your Doom Emacs configuration.

  Diagnostics:
    doctor     Commands for troubleshooting and debugging Doom.
    info       Commands for troubleshooting and debugging Doom.
    version    Show installed versions of Doom, Doom modules, and Emacs.

  Development:
    ci         Commands for developing or launching Doom.
    make       Commands for developing or launching Doom.
    run        Commands for developing or launching Doom.

See 'doom h[elp]' or 'doom {-?,--help}' for documentation.

~/.config/emacs > ./bin/doom install
Error: a subcommand is required

Available commands:


See 'doom h[elp] install' or 'doom install {-?,--help}' for documentation.

~/.config/emacs > EMACS=/usr/bin/emacs ./bin/doom install
Error: a subcommand is required

Available commands:


See 'doom h[elp] install' or 'doom install {-?,--help}' for documentation.
```

It's currently a blocker for me at $work$, so I'm actively investigating it (and looking for alternative resolution, like having the doom install done inside a docker container), so I'm available for you should you have some additional tests in mind.

**Comment by atylermorgan** [comment]
The emacs version is also not an issue for me:

```
❯ emacs --version
GNU Emacs 29.2
Copyright (C) 2024 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
❯ git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
Cloning into '/Users/morganat/.emacs.d'...
remote: Enumerating objects: 123762, done.
remote: Counting objects: 100% (8270/8270), done.
remote: Compressing objects: 100% (1163/1163), done.
remote: Total 123762 (delta 7244), reused 7504 (delta 7105), pack-reused 115492
Receiving objects: 100% (123762/123762), 29.18 MiB | 42.08 MiB/s, done.
Resolving deltas: 100% (87619/87619), done.
❯ ~/.emacs.d/bin/doom sync
Error: a subcommand is required

Available commands:


See 'doom h[elp] sync' or 'doom sync {-?,--help}' for documentation.
```

I am also using emacs/doom for work, so to get things online, I did the following:

1. checkout an older version of doom (chosen kind of randomly. this is the version that is working on another one of my computers):
```git checkout 35865ef5e -b develop```
2. install
```~/.emacs.d/bin/doom install```
3. I get the same error as above `(void-function string-remove-suffix)`, so I added `(require 'subr-x)` near the top of `~/.emacs.d/init.el`.
4. sync
```~/.emacs.d/bin/doom sync```

This works for right now, but I'm not really sure what to do to help with debugging the `Error: a subcommand is required` issue. I have reproduced the issue with `emacs-plus` on my Mac Mini w/ M2 Pro, as well as an Macbook Pro w/ Intel i5. If there is anything we can do, please let us know.

**Comment by bpizzi** [comment]
@hlissner some feedback for you, as I see you worked on that.

First, I've not been able to reproduce in a fresh Archlinux container (Docker).
With a Dockerfile that looks like that:
```
      FROM archlinux:base
      RUN pacman -Sy --noconfirm
      RUN pacman -S --noconfirm archlinux-keyring git
```

I can reliably run `doom install` on a freshly cloned doom's repo (well, apart from yesterday, when a transient glitch with straight perturbed the communication with github.com during `doom install`, don't ask why, Murphy's law I guess).

So it's clearly something that has to do with something more than the version of Emacs itself.

Then, after abusing uninstalling and reinstalling all the versions of Emacs I could lay my hands on (including 29.2, 29.1, 28.2, all in nativecomp and nox, from both package manager and compiling from source), I've finally been able to have a working `doom install`, and I'm really not sure why.

I vividly remember that, the first time it worked, there was a `EMACS=/usr/bin/emacs ` prepended in the shell's command, but I'm not sure it's related.

As a matter of fact, it was with 29.1, downgraded from the local cache of my package manager.
Which leaves me with, right now, a working Doom Emacs installation on this computer \o/.

However, as I'm a man without fear - to my detriment, I've done some more tests :
- first I uninstalled Emacs 29.1, and reinstalled 29.2 from package manager : `Error: a subcommand is required` comes back,
- then uninstalled 29.2 and reinstalled 29.1 from the local cache: the error is still here,
- then `git pull` on `.config/emacs` in order to get your last commit (currently on a24845, which includes f55131): and sadly the error is still here.

But at least I can work, because 29.1 is working well with the `.config/emacs` resulting from the working `doom install` I've managed to get yesterday.

I can also add that there something clearly wrong with Doom on the `emacs 29.2-1` [published](https://gitlab.archlinux.org/archlinux/packaging/packages/emacs/-/commits/main) by Archlinux some days ago.

The reason why I've tried to `doom install` in the first place yesterday morning is that I've previously ran `pacman -Syu`, where `emacs 29.2-1` came in as a replacement for `emacs 29.1-1`, and it broke Doom Emacs.
Emacs alone (`emacs -Q`) could still start without problem, but my doom config rendered a blank, apparently stuck emacs with a empty window.

And now that I've managed to get again a working `.config/emacs` with `doom install`, I can only start Emacs with it's downgraded 29.1 package: the 29.2 package still has the same bug as before.

**Comment by bpizzi** [comment]
@hlissner Damn, I've found the culprit!

At least I can reliably reproduce a working workaround.
Exploring my `history` in order to understand why it worked, it appears that I've tried `printenv | grep emacs` which brings `DOOMPATH=/home/xxx/.config/emacs/bin`, after which I've `export DOOMPATH=` in order to remove this env var, and it works: that's what brings `doom sync/install` back to life.

And, now that I can `doom sync`, I no longer have this bug on `29.2-1` where the window would be stuck empty: it was just the case of a non-synced doom.

Hope it helps.

**Comment by bpizzi** [comment]
One more piece of clue: searching Doom's source for `DOOMPATH`, I've stumbled upon [Empty entries in DOOMPATH are replaced with the $EMACSDIR/cli/.](https://github.com/doomemacs/doomemacs/blob/master/lisp/doom-cli.el#L102), and `$EMACSDIR` is **not** set in my env.

**Comment by atylermorgan** [comment]
Nice job, @bpizzi!

Yes, this works for me on emacs-plus (29.2), too:

```
❯ git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
❯ echo $DOOMPATH
/Users/username/.emacs.d/bin
❯ ~/.emacs.d/bin/doom install
Error: a subcommand is required

Available commands:


See 'doom h[elp] install' or 'doom install {-?,--help}' for documentation.
❯ DOOMPATH=
❯ echo $DOOMPATH

❯ ~/.emacs.d/bin/doom install
Installing Doom Emacs!

- Skipping ~/.doom.d/ (already exists)
  - Skipping init.el (already exists)
  - Skipping config.el (already exists)
  - Skipping packages.el (already exists)
Generate an envvar file? (see `doom help env` for details) (y or n)
```

**Comment by hlissner** [comment]
@bpizzi Good catch. That helped me zero in on the issue (`DOOMPATH` getting set to something that omits Doom's built-in CLI library). It doesn't answer why `DOOMPATH` was set in your shell, though, unless you're running these commands from a shell (or eshell) from inside Doom Emacs where that variable could be set in the envvar file (which is generated on `doom install`, unless you refuse the prompt to).

In any case, 90dae25 ensures `DOOMPATH` is no longer written to that envvar file anymore, so that edge case should bite anyone anymore either.

**Comment by bpizzi** [comment]
> It doesn't answer why DOOMPATH was set in your shell

Ho, I found that this morning :

```
> rg DOOMPATH .config
.config/environment.d/envvars.conf
4:DOOMPATH=/home/bp/.config/emacs/bin
```

I may have put it there long ago while messing with chemacs2 I guess...

> In any case, https://github.com/doomemacs/doomemacs/commit/90dae2594042ac73ea7e38fb044917e153e9ebeb ensures DOOMPATH is no longer written to that envvar file anymore, so that edge case should bite anyone anymore either.

And I can confirm that it works ;)

Thanks a lot!
