### ISSUE TITLE
Unable to unbind `C-z`

### ISSUE THREAD

**Issue by Anskrevy** [doomemacs/doomemacs#7671]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Unbind `C-z` 

```elisp
(after! evil
  (setq evil-toggle-key nil)
  (global-set-key (kbd "C-z") nil)
  (evil-global-set-key 'normal (kbd "C-z") nil))
(map! :after evil
      "C-z" nil)
```

Expect nothing to happen when pressing `C-z`.

### Current behavior

`C-z` does not show up when searched under `SPC h b b`, but pressing `C-z` still results in `evil-emacs-state` being toggled.

### Steps to reproduce

1. Complete a fresh install of doom.
2. Add the code above to `config.el`.
3. Keybind does not seem present but works as though no change had been made.

Maybe I'm not unbinding `C-z` correctly, but this seems like a lot of effort for something I just want to turn off.

### System Information

https://gist.github.com/Anskrevy/431b5aeb0f4a59223e050d5c0fed6b87

**Comment by GinShio** [comment]
Sorry I do not use evil. I unbind `C-z` used `(global-unset-key (kbd "C-z"))`.

**Comment by hlissner** [comment]
It's a good idea to use `C-h k [KEY]` to determine where a keybind might be bound. In `C-z`'s case, its' on `evil-insert-state-map` and `evil-motion-state-map`, so any of these would work:

```elisp
;; option 1
(define-key evil-insert-state-map "C-z" nil)
(define-key evil-motion-state-map "C-z" nil)

;; option 2
(evil-define-key '(insert motion) 'global "C-z" nil)

;; option 3
(map! :im "C-z" nil)
```

The `(after! evil ...)` is unnecessary, since Doom loads it immediately (i.e. it will be loaded by the time your $DOOMDIR/config.el is read.)

----

Anyhow, I will close this since this isn't a bug. Please use our [Discourse](https://discourse.doomemacs.org) or [Discord](https://doomemacs.org/discord) for support questions like these; our issue tracker is for bug reports.

**Comment by Anskrevy** [comment]
That's my bad. I should have dug a bit more. Thank you very much!
