### ISSUE TITLE
Missed module: gist

### ISSUE THREAD

**Issue by oupfiz5** [doomemacs/doomemacs#7708]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

No get message in process of sync

``` sh
./doom sync
! Failed to locate a ':tools gist' module
```

The repo https://github.com/doomemacs/doomemacs/tree/master/modules/tools doesn't contain directory gist.

### Current behavior

! Failed to locate a ':tools gist' module

### Steps to reproduce

1. uncomment gist in `init.el`
2.  execute command `./doom sync`
3. Got message `! Failed to locate a ':tools gist' module`

### System Information

https://gist.github.com/oupfiz5/6843badbe69db2c99d597cbdf31c0cba

**Comment by hlissner** [comment]
The gist module was removed in https://github.com/doomemacs/doomemacs/commit/53998a024965ddb328e9deea38c1e4089a1e5bb2 because the [gist.el](https://github.com/defunkt/gist.el) package is no longer maintained, nor does it work anymore (uses an old, unsupported authentication method for Github, iirc). If you installed Doom a long time ago, it would've deployed an old module list that includes `gist`. Doom doesn't alter this list when upgrading, so you have to remove it from yourself. 

In any case, the gist module will eventually be replaced with a more general one (designed for interacting with most pastebin services, *including* gist), likely powered by webpaste.el or similar. And I'm working on more helpful warnings for removed modules, but for the time being, the gist module is gone. If you want, you can try your luck by installing the gist.el package yourself; it's still on MELPA and can be installed manually.
