### ISSUE TITLE
Doom keep on compiling over and over a few packages on startup

### ISSUE THREAD

**Issue by jman-schief** [doomemacs/doomemacs#7920]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

When Doom in installed and configured, I expect no more bytecode compilation.

### Current behavior

Everytime I start Doom, the following packages get recompiled:

<details><summary>Full *Async-native-compile-log* buffer</summary>
<p>

Compiling /usr/share/emacs/29.4/lisp/emacs-lisp/subr-x.el.gz...
uncompressing subr-x.el.gz...
uncompressing subr-x.el.gz...done
Compiling /usr/share/emacs/29.4/lisp/emacs-lisp/pcase.el.gz...
uncompressing pcase.el.gz...
uncompressing pcase.el.gz...done
Compiling /usr/share/emacs/29.4/lisp/emacs-lisp/gv.el.gz...
uncompressing gv.el.gz...
uncompressing gv.el.gz...done
Compiling /usr/share/emacs/29.4/lisp/emacs-lisp/cl-lib.el.gz...
uncompressing cl-lib.el.gz...
uncompressing cl-lib.el.gz...done
Compiling /usr/share/emacs/29.4/lisp/emacs-lisp/cl-loaddefs.el.gz...
uncompressing cl-loaddefs.el.gz...
uncompressing cl-loaddefs.el.gz...done
Compiling /usr/share/emacs/29.4/lisp/emacs-lisp/cl-macs.el.gz...
uncompressing cl-macs.el.gz...
uncompressing cl-macs.el.gz...done
Compiling /usr/share/emacs/29.4/lisp/emacs-lisp/cl-seq.el.gz...
uncompressing cl-seq.el.gz...
uncompressing cl-seq.el.gz...done
Compiling /usr/share/emacs/29.4/lisp/net/tramp-loaddefs.el.gz...
uncompressing tramp-loaddefs.el.gz...
uncompressing tramp-loaddefs.el.gz...done
Compilation finished.

</p>
</details> 

### Steps to reproduce

1. Open Doom
2. go and check the `*Async-native-compile-log*` buffer

### System Information

https://paste.sr.ht/~jman/a50ff018cb6217373b300fc1a0975b862f8ad04f

**Comment by hlissner** [comment]
I can't reproduce this on any of my test environments (Arch Linux, Ubuntu, NixOS, MacOS, and Windows; on 28.2, 29.3, 30.0.50, or 31.0.50), so I suspect a local issue (e.g. an issue with the Emacs package served by your OS package manager).

A few things to try:

1. Delete your envvar file (i.e. run `doom env clear`) -- it might've captured an Emacs envvar, like `EMACSLOADPATH`, `EMACSPATH`, `EMACSDOC`, etc.
2. Make sure you haven't modified any `native-comp-*` variables in your config, particularly `native-comp-jit-compilation-deny-list` or `native-comp-deferred-compilation-deny-list`.
3. It's possible that those packages are natively compiled *before* Doom loads, typically because a site-lisp package (installed via your OS package manager, rather than from within Doom/Emacs), like mu4e or vterm, loads them before Doom starts up. If you have any of these, try uninstalling them and see if the issue goes away. If it does, this is an issue for whomever maintains the Emacs package for your distro's package manager.
4. Try disabling deferred/async compilation by adding `(setq native-comp-jit-compilation nil)` to `$DOOMDIR/init.el`.
5. Are you absolutely sure you're starting the same Emacs as you `doom sync`ed with? I.e. Your `doom info` shows `EMACS=/usr/bin/emacs`, but does your `M-x doom/info` show the same?

**Comment by peterhoeg** [comment]
I have seen this too and it was "fixed" by blowing away all the local build directories and native comp build caches. Then `doom sync` and things were back to normal.

This was emacs 29.3

**Comment by dwinkler1** [comment]
@peterhoeg could you please elaborate on which directories you deleted?

**Comment by hlissner** [comment]
@dwinkler1:

```sh
# EMACSDIR = where you cloned Doom, e.g. ~/.emacs.d or ~/.config/emacs
rm -rf $EMACSDIR/.local/straight/build-*
rm -rf $EMACSDIR/.local/cache/eln/*

doom sync
```

**Comment by dwinkler1** [comment]
Thank you!

**Comment by hlissner** [comment]
See if recompiling your packages ahead-of-time fixes the issue. I.e.

```sh
doom sync --gc --rebuild --aot
```

This will clean up any orphaned build artifacts, rebuild your installed packages, and native-compile all your packages. (Warning: this might take 10-50min depending your CPU)

**Comment by 0WD0** [comment]
I encountered the same issue and found a solution:

Add the following to early-init.el:

```elisp
(when (featurep 'native-compile)
  (add-to-list 'native-comp-eln-load-path 
               (expand-file-name ".local/cache/eln/" user-emacs-directory)))
```
