### ISSUE TITLE
Switch to project functionality doesn't work with Vertico / Consult

### ISSUE THREAD

**Issue by rakanalh** [doomemacs/doomemacs#7934]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Switch to project (`SPC p p`) to open a new workspace with the project name & prompt to find-file in that specific project.

### Current behavior

An error pops up:
"Please install ivy"

### Steps to reproduce

1. Configure `vertico` for completion.
2. Press `SPC p p`

### System Information

https://gist.github.com/rakanalh/b1acccc4f76f60744125f8bc42bddfd0

**Comment by hlissner** [comment]
Your `M-x doom/info` says you have `:completion ivy` enabled, but not vertico.

Did you forget to run `doom sync` after changing your `doom!` block in `$DOOMDIR/init.el`?

**Comment by rakanalh** [comment]
@hlissner apologies, i added the gist this morning when i was reporting the LSP issues.

Gist has been updated. Note that i have also installed `consult-projectile` which i have used to override switch-to-project with what that package provides. However, the issue is reproducible without.

With `consult-projectile` what happens is that a workspace does not get created (i assume it's related to `projectile-switch-project-action`... but that's a different issue for another time i guess.

**Comment by hlissner** [comment]
> However, the issue is reproducible without.

You mean, you're still getting a `"Please install ivy"` error? Since `SPC p p` works fine in vanilla Doom with the vertico module, this sounds like a config issue rather than a Doom issue, so I'll close this, but feel free to follow up here.

> With consult-projectile what happens is that a workspace does not get created (i assume it's related to projectile-switch-project-action... but that's a different issue for another time i guess.

That's to be expected. consult-projectile is unaware of and has no integration for persp-mode. I've already incorporated projectile+vertico+persp-mode integration into Doom, so anything you add to the stack will invariably be unaware of all that. Shouldn't be too hard though. If you can call `+workspaces-set-project-action-fn` and `+workspaces-switch-to-project-h` before `consult-projectile` switches to the new project, you'll have similar behavior to `SPC p p`'s current offering. I imagine consult-projectile must have a hook you can call those from.

Though, some warning, I plan to replace projectile with project.el in the not-too-near future, so I won't be working on projectile integration from here on out, and you'll need to set up projectile yourself once that happens (if you plan to stick with projectile).

**Comment by rakanalh** [comment]
You are totally right. After your replied to my other issue this morning i switched my configs to vertico but missed to remove:
```
  (setq 
        projectile-completion-system 'ivy)
```
Which is why i was getting "Please install ivy" when switching project that lead me to install consult-projectile.

Removing those, the integration seems to be working now. 

Appreciate your help. Thanks!
