### ISSUE TITLE
Treemacs ignores treemacs-persist file and always open my whole $HOME directory

### ISSUE THREAD

**Issue by neolee** [doomemacs/doomemacs#7948]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.
- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.
- [X] The issue can be reproduced on the **latest** available commit of Doom.
- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Start Emacs, `ctrl+c o p` to open `treemacs`, it should open project list as last quit, which is stored in `~/.config/emacs/.local/cache\treemacs-persist` (I've checked that file).

### Current behavior

`treemacs` open my whole $HOME directory, and change the `~/.config/emacs/.local/cache\treemacs-persist` file as below (`xxx` is my user name):
```
* Perspective main
** xxx
 - path :: ~
```

After I changed the project list (add some project remove the $HOME one, etc.), anytime I close and re-open `treemacs` it will return to the $HOME one (remove anything I added as well).

### Steps to reproduce

Start Emacs, `ctrl+c o p` (or other way) to open `treemacs`. Or close and open `treemacs` again.

### System Information

https://gist.github.com/neolee/83156729cae60401232d3d0d60536a60

**Comment by hlissner** [comment]
Technically not a bug, but I've modified the command in 3f66400 to resume the last treemacs session if the current project is $HOME (or no current valid project is found), which should reduce confusion like this and, hopefully, resolve your issue.

**Comment by neolee** [comment]
@hlissner Thanks for the quick fix!

p.s. If I'd like to use the 'display current project exclusively' mode, how can I set the 'current project'? Or if I want to quit that mode, how can I reset the 'current project'? Any doc for that feature I can use? Thanks.

**Comment by hlissner** [comment]
The current project depends on what buffer you have focused. 

- I.e. Open `~/.config/doom/some/file` and, assuming `~/.config/doom` has a project marker (like a `.git` directory, `.project` file, etc), the current project will be `~/.config/doom`,
- You can switch to another known project using `C-c p p`. If you want it to open treemacs instead of prompt you for a file, add this to `$DOOMDIR/config.el`:
  ```lisp
  (setq +workspaces-switch-project-function
        (lambda (&rest _) (treemacs-add-and-display-current-project-exclusively)))
  ```
- Alternatively, you can manipulate the project list from inside the treemacs buffer with the `M-x treemacs-add-project-to-workspace` and `M-x treemacs-remove-project-from-workspace` commands.

There's a bunch of configuration docs [in Treemacs' repo](https://github.com/Alexander-Miller/treemacs?tab=readme-ov-file#configuration). Just don't forget to wrap whatever treemacs variables you set in a `(after! treemacs ...)` block in `$DOOMDIR/config.el`.

**Comment by neolee** [comment]
Got it! Thanks for the quick and clear and elegant reply.

**Comment by hlissner** [comment]
@knl You can also get the old behavior back by rebinding `SPC o p` to `treemacs`. E.g.

```elisp
;;; in $DOOMDIR/config.el
(map! :leader "o p" #'treemacs)
;; or
(map! :leader [remap +treemacs/toggle] #'treemacs)
```
