### ISSUE TITLE
Opening files took a long time when first started Emacs after enable (default)in init.el after recent update

### ISSUE THREAD

**Issue by Ravenightwing** [doomemacs/doomemacs#7954]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

After Emacs started, it wouldn't take long to open a file.

### Current behavior

Lately, doom Emacs takes about 10 seconds to load a file (I tried org files, el files, and TeX files, and they all took a long time) when Emacs first started. After that file is loaded, it behaves normally. This didn't happen before.

I wonder if it's the intended behavior, since I don't recall waiting that long to open a file when Emacs started.

### Steps to reproduce

Set
```
:emacs
vc
```
in Emacs. (I disabled all other settings in config.el and package.el)

### System Information

https://pastebin.com/raw/xhKUP9G1

**Comment by hlissner** [comment]
A notable delay loading the packages associated with these modes the first time is normal, but 10 seconds is excessive. For me, it's, at most, 1-2s. I cannot produce a delay longer than that unless I forcibly load these things all at the same time, so I suspect it's either:

1. Caused by user configuration (I know you said you "disabled all other settings", but I don't know what you mean by that. Is your config up somewhere I can see it? Your `M-x doom/info` still says you have a `custom-file` (see `$DOOMDIR/custom.el`), which could contain code that eagerly loads packages or makes them take longer to load),
2. native-comp is [slowing down your system as it compile elisp](https://github.com/doomemacs/doomemacs/issues/7952) (it's configured to compile elisp in the background when you first load uncompiled elisp packages; this usually consumes 1/4 of your CPU cores and takes 20s-2min depending on your CPUs and the size of the package(s)) On a slower system with fewer cores, this may look like Emacs is slower, but it's the system as a whole.
3. You're using Emacs 29.1; I recommend upgrading to at least 29.3, or 30.0.50, and see if that helps. Though, I suggest you avoid 29.4, folks have reported sporadic bugs on that version.

**Comment by Ravenightwing** [comment]
> A notable delay loading the packages associated with these modes the first time is normal, but 10 seconds is excessive. For me, it's, at most, 1-2s. I cannot produce a delay longer than that unless I forcibly load these things all at the same time, so I suspect it's either:
> 
> 1. Caused by user configuration (I know you said you "disabled all other settings", but I don't know what you mean by that. Is your config up somewhere I can see it? Your `M-x doom/info` still says you have a `custom-file` (see `$DOOMDIR/custom.el`), which could contain code that eagerly loads packages or makes them take longer to load),
> 2. native-comp, which may be [slowing down your system as it compiles elisp](https://github.com/doomemacs/doomemacs/issues/7952) (it's configured to do so in the background when uncompiled elisp packages are first loaded; often consuming 1/4 of your CPU cores and taking 20s-2min depending on your CPUs and the size of the package(s)). On a slower system with fewer cores, this may slow down the whole system.
> 3. Because of Emacs 29.1; I recommend upgrading to at least 29.3, or 30.0.50, and see if that helps. Though, I suggest you avoid 29.4, folks have reported sporadic bugs on that version.

Sorry I found it's not the default module, it's the `vc` module under :emacs. After disabling this, the loading time becomes normal. Thanks anyway! 
Also, I tried again disabling customized settings (also deleted custom.el) and only enabled `vc` and `default` modules in init.el. I used without native-comp and updated to 30.0.60 (I'm not sure whether it's a version problem as you recommended 30.0.50), but it still take about ten seconds to load.
doom/info: https://pastebin.com/raw/uxdTSmWg

**Comment by hlissner** [comment]
I haven't tracked down the precise cause of this, but I suspect ded3f5e may have indirectly addressed it.
