### ISSUE TITLE
+org/insert-item-below and +org/insert-item-above do not work in terminal

### ISSUE THREAD

**Issue by jessy836** [doomemacs/doomemacs#7983]
### Current behavior

When I open an org file with emacs in terminal, and I am in a list, if I press C-RET I just get a message "No inner element". I get same message if I do C-S-RET. 

I think that the problem is that +org/insert-iteme-below  should by bound to C-RET and not to C-<return> to work in terminal and similarly for +org/insert-item-above which should be bound to C-S-RET.

I tryed to eval the following in scratch but it didn't fix the problem:

```elisp
(after! org
  (map! "C-RET" #'+org/insert-item-below))
```

### Steps to reproduce

1. emacs -nw test.org
2.  fill the file like that when |  represent the cursor:
```
#+title: Test

- [ ] one |
```
3. press C-RET, you just get the message "No inner element"
      
P.S. This is my first issu ever, so if I did something wrong or if I forgot something please let me know

### System Information
https://pastebin.com/xrnyBHHZ

**Comment by jessy836** [comment]
Sorry, don't know what happened. I tryed to fill the template but the issu is void, then I tryed to fix it, and  now the template and my addition is in a comment.

**Comment by hlissner** [comment]
This is unfortunately not a Doom issue, but a terminal one. C-RET is not a valid control character in the terminal, so the terminal won't understand it and the keypress will never reach Emacs. There is no alternative to workaround this besides using GUI Emacs, or to find another key to bind `+org/insert-item-below` and `+org/insert-item-above`. Perhaps `]o` and `[o`?

```lisp
(map! :after evil-org
      :map evil-org-mode-map
      :n "]o" #'+org/insert-item-below
      :n "[o" #'+org/insert-item-above)
```

From insert mode, you could invoke these with `C-o` (invokes a single normal-mode command before returning to insert). E.g. `C-o ] o` or `C-o [ o`.

In any case, I'll close this since this isn't a Doom issue, but feel free to follow up here.

**Comment by jessy836** [comment]
thank you, it's a pity that the terminal doesn't recognize C-RET but the workaround works, thank you very much.
