### ISSUE TITLE
Cannot install lsp for typescript: unable to install typescript via npm' because it is not present

### ISSUE THREAD

**Issue by hrqmonteiro** [doomemacs/doomemacs#7990]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

I want to install typescript language server `ts-ls`

### Current behavior

It gives me the error:

`unable to install typescript via npm' because it is not present`

![image](https://github.com/user-attachments/assets/ad404e21-b9eb-4106-a7aa-3e4889179733)

But i do have node and npm working fine:

![image](https://github.com/user-attachments/assets/96a9080a-cf09-4d17-8804-81f8f67e5f86)

### Steps to reproduce

1 - Open emacs
2 - `M-x lsp-install-server`
3 - Select `ts-ls`

### System Information

https://pastebin.com/NY4dmBSh

**Comment by hlissner** [comment]
Your `M-x doom/info` tells me you have an envvar file present (likely because you typed 'y' when it asked you if you wanted to generate one when you ran `doom install`, or if you manually generated one by running `doom env`).

The envvar file is a dump of your shell environment, including your `$PATH`. If your `$PATH` has changed since you installed `npm`, then it won't be in the `$PATH` that Emacs sees. 

Regenerate your envvar file by running `doom env`.

As this isn't a Doom bug, I'll close this, but feel free to follow up here.
