### ISSUE TITLE
Magit: Couldn't collect commit list because: fatal: bad object cf94190410ef163fd102cdbcb67f28599d31eabc

### ISSUE THREAD

**Issue by LeoAdL** [doomemacs/doomemacs#8007]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Upgrade of Magit proceeds without errors. 

### Current behavior

Error when running doom sync in my shell 
```sh
$ doom sync                                                                                                                                                    
> Synchronizing "default" profile...
  > Regenerating envvars file
    ✓ Generated ~/.config/emacs/.local/env
  > Ensuring packages are installed and built...
    - No packages need attention
  > Updating pinned packages...
    > (50/267) Re-cloning magit...
      > Cloning magit (for magit-section)...
    ✓ (50/267) magit: 55656a3 -> cf94190 [1 commit(s)] (w/ 5 dependents)
        ERROR: Couldn't collect commit list because: fatal: bad object cf94190410ef163fd102cdbcb67f28599d31eabc
```

As mentioned here: https://github.com/magit/magit/issues/5204 , pinning to "main" branch instead of Melpa solves the issue.
```emacs-lisp
(package! magit
  :recipe (:host github :repo "magit/magit" :branch "main"))
```

Tagging @tarsius for further info

### Steps to reproduce

1. Open terminal.
2. Run "doom sync" or "doom upgrade"

### System Information

https://gist.github.com/LeoAdL/9cb38669bb07ac7a7c23b1ff9374b3c4

**Comment by hlissner** [comment]
Seems magit/magit@cf94190410ef was rebased/force pushed out of the repo, so I've bumped the module again in 5e70fe1. Thanks for letting me know!

**Comment by tk-nguyen** [comment]
> Seems [magit/magit@cf94190410ef](https://github.com/magit/magit/commit/cf94190410ef) was rebased/force pushed out of the repo, so I've bumped the module again in [5e70fe1](https://github.com/doomemacs/doomemacs/commit/5e70fe169764bd272e73adbe56d67251fe9a886a). Thanks for letting me know!

I think https://github.com/magit/magit/commit/3b37048688e5 is forced pushed out of the repo again. The same error is present: 
```bash
  > Updating pinned packages...
    > (36/260) Re-cloning magit...
      > Cloning magit (for magit-section)...
    ✓ (36/260) magit: 2da34f1 -> 3b37048 [1 commit(s)] (w/ 5 dependents)
        ERROR: Couldn't collect commit list because: fatal: bad object 3b37048688e50ba5897945ce08eeaed34433c9b7
```

**Comment by hlissner** [comment]
Whoops. Just realized that the HEAD of magit's melpa branch is automatically generated and rebased to the front every time `main` is updated, so tracking it will inevitably result in breakage. I've repinned it to HEAD~1, which should resolve the issue.

**Comment by tarsius** [comment]
I author my info manuals in org. Because support for generating texi files from org files was lacking or completely missing from various relevant tools and projects, the generated texi file unfortunately had to be checked into git as well. After several years of improving the situation, I have finally decided to remove the generated files.

I have implement support for exporting texi to org in `package-build.el`, which is used to build the packages distributed on Melpa. I am the maintainer of that, but I am only a deputy maintainer of Melpa. Unfortunately, though understandably, the main maintainers of Melpa did not want to add that functionality to Melpa.

So I have no choice but to continue to generate the texi files on my end. However, I do not want to keep these files on the `main` branch, and created the dedicated `melpa` branch.

This `melpa` branch, as implied by its name, is only intended to be used by Melpa, but other projects that use Melpa's recipes don't know that they should ignore `:branch "melpa"`. I do recommend that such Melpa downstreams treat this value differently, i.e., that they add a special case to ignore that particular value. (And I should probably implement support for that directly in `package-build.el`.)

As you have noticed, the `HEAD` commit of `melpa` is always exactly one commit ahead of `main`. The commit message also says so much: `Publish for Melpa (always "main" + one commit)`. However, to be on the safe side:

> ```elisp
> ;; NOTE: Always bump this to HEAD~1, not HEAD, because the latest commit on
> ;;   magit's melpa branch is auto-generated and moved to HEAD every time there's
> ;;   a commit to its main branch.
> ```

bump to `origin/main` instead of `HEAD~`. Currently these are the same commit, but it is possible that there will be more "melpa-only" commits with generated changes in the future.

Since the branch, you are now pinning to, does *not* include the texi files, you have to arrange for them to generate locally. I believe adding `:pre-build ("make" "texi")` to the recipe should do that.

This affects all of my packages that have a manual. They should all be adjusted accordingly in Doom. The packages are: `borg`, `epkg`, `forge`, `ghub`, `magit`, `magit-section`, `transient` and `with-editor`.

**Comment by panchoh** [comment]
I wonder, @hlissner, if you have seen @tarsius’  [comment](https://github.com/doomemacs/doomemacs/issues/8007#issuecomment-2302177459), regarding which branch to use (`main`), and why, as well as the affected packages (e.g. `with-editor` just blew when I updated this morning).

As per the comments you have written on 1b336d05491, I'd say this info hasn't reached you.

(Happy to do a PR with the affected packages, just whistle!)

**Comment by hlissner** [comment]
Ah, I had not, no, but give me some time to look into this. It might warrant a more systematic fix than a few recipe corrections, because:

- This will bite any user that manually installs any package that depends on these packages (that Doom doesn't have a module for to handle this issue for them), 
- I want to avoid having `package!` statements for 2nd+ order dependencies (`transient`, for example, is used [in *quite* a lot of places](https://melpa.org/#/transient), which would mean a `package!` statement is needed in any module that depends on one of these packages) 
- And I don't want to impose GNU Make+texi dependencies on users (especially our Windows users) to install packages.

So it might be something for @doomelpa to deal with when I get around to it, or something @emacs-straight might consider taking on (much like how it has with https://github.com/emacs-straight/org), but I'll revisit that when I get around to this.

**Comment by tarsius** [comment]
@hlissner I've given up on not checking in generated files for now. You can once more use the `main` branch but since that is not a fast-forward from the dropped `melpa` branch, you'll have to update the pin one more time. After that, things should be back to normal.
