### ISSUE TITLE
Indent bars should not be showing in ediff

### ISSUE THREAD

**Issue by nqminhuit** [doomemacs/doomemacs#8074]
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

Indent bars should not be showing when using ediff to avoid noisy information

### Current behavior

![image](https://github.com/user-attachments/assets/213c3d51-7cee-4384-bc43-155b3d006e92)

### Steps to reproduce

1. activate `indent-guides` module
2. using "edif" function on any magit buffer (logs, status)
3. navigate to some diff region and observer

(I am using **Emacs 30.0.91** btw)

### System Information

https://gist.github.com/nqminhuit/e38db1444d91743310df9cdd2f3ae1eb

**Comment by hlissner** [comment]
I agree it's noisier, but harmless and still potentially useful at indicating indentation levels (as is its job). Since I don't consider this a bug, I won't be addressing this.

That said, Doom introduced a `+indent-guides-inhibit-functions` variable. Adding a predicate function to detect `ediff-temp-file-mode` should disable `indent-bars-mode` in ediff buffers for you:

```elisp
;;; Add to $DOOMDIR/config.el
(add-hook! '+indent-guides-inhibit-functions (bound-and-true-p ediff-temp-file-mode))
```

Thanks for bringing it to my attention, in any case!
