### ISSUE TITLE
Commit `2b0013db`: cannot load the `coq` layer

### ISSUE THREAD

**Issue by abgruszecki** [doomemacs/doomemacs#8169]
### I confirm that...

- [x] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [x] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [x] The issue can be reproduced on the **latest** available commit of Doom.

- [x] The issue can be reproduced on a stable release of Emacs, such as 27, 28, or 29. *(Unstable versions end in .50, .60, or .9x)*

### Expected behavior

I can load the `coq` layer.

### Current behavior

An error occurs if I enable the coq layer. This happens even if I have no custom config (empty config.el, packages.el). This is the error: https://gist.github.com/abgruszecki/c3f3d415954f68f783942d8f148ffab0 . Note that I cut out L5, it seems to contain let-bindings for many (all?) autoloads, even without expanding all the ellipses in the backtrace it's 9x as large as the entire rest of the file. Let me know if you need it and I'll upload it.

### Steps to reproduce

Start Emacs with the `coq` layer enabled on the specified Doom commit.

### System Information

https://gist.github.com/abgruszecki/e22899a84b7691f11506b8a0a11bec66

**Comment by hlissner** [comment]
Seems `proof-general` is doing something [quite unconventional in its autoloads](https://github.com/ProofGeneral/PG/blob/master/proof-general.el#L58-L70). The problem is that it's wrapping that bit in `eval-and-compile`, which removes it from the normal execution context (so `load-file-name` won't be correct in the case of the mega autoloads file that Doom produces). This seems to have been acknowledged (indirectly) in https://github.com/ProofGeneral/PG/issues/771, and the solution they're working on there will fix this issue, but until then I'll look into deploying a workaround to our module.

Please test the following and let me know if it works around the issue for you:

```elisp
;;; add to $DOOMDIR/packages.el

(package! proof-general
  :pin "3a99da275523c8f844fdfa3dd073295eece939f3"
  :recipe (:build (:not autoloads)))
```

```
;;; add to $DOOMDIR/autoload.el

;;;###autoload
(after! proof-general
  (require 'proof-site
           (expand-file-name "generic/proof-site"
                             (file-name-directory (locate-library "proof-general")))))
```

**Comment by hlissner** [comment]
As of [7533707](https://github.com/doomemacs/doomemacs/commit/7533707e0057fec56d04681eb327541c4163ab92) this should be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Comment by abgruszecki** [comment]
After `doom upgrade` everything works. Thanks a lot @hlissner, for prompt responses and for Doom too! It's a pleasure to use it :)
